### PR TITLE
Create DogeADA token

### PR DESCRIPTION
**Pull request by DogeAda**
Meme token - DogeADA token - Cardano

# Pull Request Template

## Description

Registration request for DogeADA Token

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by cleanerm5** [comment]
Hi @DogeAda 

you need to rename the file to b4273f1d8d0021d188784c3d72dc514f602b7ab8cfb87e3134550c42446f6765414441.json (the subject must be the file name). Sorry for the inconvenience.

**Comment by DogeAda** [comment]
Hi,
I cant edit. Is here I have to do?

[image: image.png]

Best regards,
Paulo Santos

cleanerm5 ***@***.***> escreveu no dia segunda, 31/01/2022
à(s) 18:08:

**Comment by DogeAda** [comment]
> Hi @DogeAda
> 
> you need to rename the file to b4273f1d8d0021d188784c3d72dc514f602b7ab8cfb87e3134550c42446f6765414441.json (the subject must be the file name). Sorry for the inconvenience.

Did it right?

**Comment by cleanerm5** [comment]
unfortunately not.n in PR #1401 the filename was good but it was in the root folder and not the mappings subfolder.

**Comment by DogeAda** [comment]
Hi, good morning!

Now iam a litle lost.
#1402 is correct?
Can I use #1402 ? I think its correct and i think is on mapping.
And Delet #1401?

[image: image.png]

Best regards,
Paulo Santos


cleanerm5 ***@***.***> escreveu no dia terça, 1/02/2022 à(s)
00:05:

**Comment by cleanerm5** [comment]
Hi @DogeAda 

I merged the contents of the first try in #1401 with #1411

Your token metadata should be listed as soon as the backend syncs the data (which could take up to 4 hours).

**Comment by DogeAda** [comment]
Thanks for your help :)

Have a nice day!

Best regards,
Paulo Santos

cleanerm5 ***@***.***> escreveu no dia terça, 1/02/2022 à(s)
09:27:

**Pull request closed without merging**
