### PR TITLE
remove ray suit tokens because they should be NFTs

### PR DESCRIPTION
**Pull request by cardano-tools-nft**
# Pull Request Template

## Description

Remove ray suit tokens because they should be NFTs.

## Type of change

- [x ] Metadata related change
- [ ] Other

## Checklist:

- [x ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by TheCaptRay** [comment]
@cleanerm5 Please merge this request. It removes token registry because they are intended to be NFTs.

Thank you.

**Comment by TheCaptRay** [comment]
@cleanerm5 Hi. I would really appreciate if you could merge this as soon as possible, since, my mint is live now and the previews aren't visible on Pool.Pm. That's why have to remove the token registry metadata, so that they can be visible as NFT GIFs. 

Thank you.

**Comment by cleanerm5** [comment]
Hi @TheCaptRay 

could you please file one PR where you change the "name" property of one of the files to a value of "VOID", increment the corresponding sequenceNumber by 1, sign the file again and then commit/PR it? That way you prove the provenance of the metadata is yours.

That is the procedure described here https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-delete-my-entry-from-the-registry%3F which shall prevent others from deleting metadata for subjects they don't own.

But only for one of the files please. We make an exception from the "process" here.

**Comment by TheCaptRay** [comment]
> Hi @TheCaptRay
> 
> could you please file one PR where you change the "name" property of one of the files to a value of "VOID", increment the corresponding sequenceNumber by 1, sign the file again and then commit/PR it? That way you prove the provenance of the metadata is yours.
> 
> That is the procedure described here https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-delete-my-entry-from-the-registry%3F which shall prevent others from deleting metadata for subjects they don't own.
> 
> But only for one of the files please. We make an exception from the "process" here.

I used Cardano Tools to do that. And the PR was done by Peter from Euro Pool (owner of Cardano Tools). I'll try to do what you ask, I'm really noob at this, so I'm sorry if I didn't get it.

I'll try. These are all my NFT metadata. You can find the name of Artist as well.

**Comment by cardano-tools-nft** [comment]
Hi @cleanerm5 i've created an according PR here: https://github.com/cardano-foundation/cardano-token-registry/pull/1488

**Comment by TheCaptRay** [comment]
@cleanerm5 

The pull request as you mentioned - 

https://github.com/cardano-foundation/cardano-token-registry/pull/1488

Thank you.

**Review by cleanerm5 — APPROVED** [review]

**Pull request merged**
