### PR TITLE
deprecate v1tuna and add tuna v2

### PR DESCRIPTION
**Pull request by rvcas**
# Pull Request Template

## Description

TUNA V2 is live and people are mining. We have a new policy ID that I am adding in this PR and I am also adding an ugly name to the old policy so that it's clear and doesn't confuse people.

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Review by linconvidal — CHANGES_REQUESTED** [review]
Hey @rvcas! For each property changed (the old policy), you need to bump the sequence number and sign it again to pass the validation stage.

**Comment by rvcas** [comment]
no problem

**Comment by Godspeed-exe** [comment]
**Automated feedback**<br /><br />**Value:** <br />V1TUNA<br /><br />**Attribute:** <br />ticker<br /><br />**Analysis:** <br />There is no immediate indication that 'V1TUNA' is impersonating a well-known individual or brand within the Cardano ecosystem or the wider crypto ecosystem. It does not directly reference any recognized names or brands.<br /><br />**Value:** <br />please check files manually<br /><br />**Attribute:** <br />logo<br /><br />**Analysis:** <br />The image contains a stylized logo featuring the letter 'F' with a partial circular design around it. This could be an identifiable logo of a brand or organization.<br /><br />**Value:** <br />please check files manually<br /><br />**Attribute:** <br />logo<br /><br />**Analysis:** <br />This image appears to be a logo consisting of the letter 'F' stylized with a surrounding partial circular element. Please check for copyright or brand usage infringement, specifically in the context of recognizable logos.<br /><br />

**Comment by theeldermillenial** [comment]
@linconvidal Looks like update was made. Bumping :)

**Review by linconvidal — APPROVED** [review]

**Pull request merged**
