### PR TITLE
Prevent validation Github action to check on other files than in the PR of interest.

### PR DESCRIPTION
**Pull request by cleanerm5**
# Pull Request Template

## Description

This PR addresses #1121 by doing the git diff within the validation Github action on ${{ github.event.pull_request.base.sha }} variable rather than the current head of the master.

## Type of change

- [ ] Metadata related change
- [x] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by sevanspowell** [comment]
Very interesting. I'm going to have to investigate a little further, but thanks for your work. Get back to you soon.

**Comment by sevanspowell** [comment]
Didn't get a chance to look into this today, will take another look on Monday.

**Comment by cleanerm5** [comment]
@sevanspowell "inspiration" for the solution is based on this thread[Ho to get base sha when using pull request target](https://github.community/t/how-to-get-base-sha-when-using-pull-request-target/142021/11) which also refers to some security issues related to checking out PRs from forked repos [Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)

I guess the latter shouldn't be a problem as we check that the commit does only contain changes in the mappings folder.

**Comment by thegalgos** [comment]
@sevanspowell I'm facing this problem, my PR is not passing because it is checking files from other PR, this is the run:
https://github.com/cardano-foundation/cardano-token-registry/runs/4894096627?check_suite_focus=true
Should check "The Galgos Token" though it is failing because of "harmlesscoin"

Thanks!

**Comment by sevanspowell** [comment]
Thanks for your work on this!

I did some testing and `${{ github.event.pull_request.base.sha }}` didn't work how I expected. It turns out HEAD is exactly what we need (we're looking for the HEAD of the pull-request). I opened up this PR to fix it: https://github.com/cardano-foundation/cardano-token-registry/pull/1256.

**Comment by cleanerm5** [comment]
Closing this PR due to correct solution in #1256

**Pull request closed without merging**
