### PR TITLE
Paribus

### PR DESCRIPTION
**Pull request by Simon0x**
# Pull Request Template

## Description

PBX is the utility token of Paribus.io
We started on Ethereum but we are now preparing our steps for Cardano.

Our token was minted  by a fixed supply policy script provide by the WingRiders minter. Therefor we don't have the signing keys.
The tool can be found here: https://github.com/wingriders/minter

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [x] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by jsyme222** [comment]
I'm pretty sure you need need valid key signatures in order to be approved.

`token-metadata-creator entry $SUBJECT -a policy/policy.skey`

**Comment by Simon0x** [comment]
@jsyme222 

This token was minted by the tool at https://minter.wingriders.com/ 
You only connect your wallet there and a Plutus script mints the token for you. Therefore I don't have the possibility to generate valid signatures for the above token information. Thats why I wrote it in the above description of the issue.

**Comment by jsyme222** [comment]
Interesting, I understand the situation now - I'm not sure how they can verify the validity of the information without key signatures. Otherwise, what stops me or anyone else from sending in a PR to update your token with bogus data?  

Have you successfully submitted token metadata for tokens minted this way before?

**Comment by Simon0x** [comment]
I personally didn't. 
But we worked together with the WingRiders team and they guided us on this workflow. So I assume this isn't the first time a token was minted in this way.

**Comment by Simon0x** [comment]
I personally didn't. 
But we worked together with the WingRiders team and they guided us on this workflow. So I assume this isn't the first time a token was minted in this way.

Edit

Example for their own token: https://github.com/cardano-foundation/cardano-token-registry/blob/master/mappings/c0ee29a85b13209423b10447d3c2e6a50641a15c57770e27cb9d507357696e67526964657273.json

**Comment by cleanerm5** [comment]
I can confirm this. The minting policy based validation process does not accord for assets being minted by smart contracts. Actually the minting policy based validation is just 1 out of multiple validation "paths" within CIP-26. WingRiders has already registered their token this way.

**Review by cleanerm5 — APPROVED** [review]

**Pull request merged**
