### PR TITLE
Create 8ee6a10504961bac6531d79bb32a616187252fece59dc0ac9019645159454554

### PR DESCRIPTION
**Pull request by YeetCoinAda**
# Pull Request Template

## Add this new coin

Please include a short summary of the changes in this PR.

## Adding new coin

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by YeetCoinAda** [comment]
Hi

**Comment by cleanerm5** [comment]
Hi @YeetCoinAda 

Your file is missing the right file ending. Please add ".json" to the submitted file name.

**Comment by YeetCoinAda** [comment]
Will do, thanks

**Comment by YeetCoinAda** [comment]
Is that correct?

**Pull request merged**
