### PR TITLE
Filip own token submission

### PR DESCRIPTION
**Pull request by rastaboys**
# Pull Request Template

## Description

Registration request for FIL native token

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by rastaboys** [comment]
Hi can please someone aprove? thank you very much

**Review by crptmppt — CHANGES_REQUESTED** [review]
Right now PRs have to be manually processed and have a separate review setup which cannot handle multiple files. Accordingly PRs with more than one mapping file will be closed to prevent overloading the process.
Thank you for resubmitting your mappings as individual PRs for processing (making sure they clear the automated checks!)

**Comment by rastaboys** [comment]
I dont understand why my request is not granted

**Comment by rastaboys** [comment]
need to add one by one

**Pull request closed without merging**
