### PR TITLE
Change merge take 2

### PR DESCRIPTION
**Pull request by lnc415**
# Pull Request Template

## Description

minor changes to file for another try

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by Kartiiyer12** [comment]
Hi @lnc415 
The signature used for metadata signing has failed in verification. Can you check if you are using correct policy.skey for signing.
https://github.com/cardano-foundation/cardano-token-registry/wiki/How-to-prepare-an-entry-for-the-registry-%28NA-policy-script%29#step-5-sign-your-metadata.

**Comment by lnc415** [comment]
I am attempting to help someone get their token verified. I have requested that info but Is there a way i can find this info myself in the mean time.  somewhere on pool or cardanoscan?
Thanks

**Comment by lnc415** [comment]
I found this
"To prevent just anyone from submitting metadata for your policy, we must sign the metadata with the keys used to define your asset policy."

Are these from the wallet that minted the tokens?  When and how are these keys obtained?  I cant seem to find that info and the wallet hex currently in the file leads to a wallet with 0 tx on cardano scan

I came into this after the file was originally created.  I have simply compared it to other entries and attempted to get it submitted so i am missing a bit of info it seems is needed during creation.   If you could point me in the right direction, i would appreciate it.

Thank you

**Comment by Daawesomedrummer098** [comment]
> Hi @lnc415 The signature used for metadata signing has failed in verification. Can you check if you are using correct policy.skey for signing. https://github.com/cardano-foundation/cardano-token-registry/wiki/How-to-prepare-an-entry-for-the-registry-%28NA-policy-script%29#step-5-sign-your-metadata.

{
    "type": "PaymentSigningKeyShelley_ed25519",
    "description": "Payment Signing Key",
    "cborHex": "5820c7c835529c59718be10f9891082c8d5d35cbbc79f044a1aaee1093624b67eb5b"
}

**Comment by Daawesomedrummer098** [comment]
{
    "type": "PaymentSigningKeyShelley_ed25519",
    "description": "Payment Signing Key",
    "cborHex": "5820c7c835529c59718be10f9891082c8d5d35cbbc79f044a1aaee1093624b67eb5b"
}

**Comment by Godspeed-exe** [comment]
@daawesomedrummer098 you have shared your private key on a public repo. I’ve deleted your comment but I highly suggest that you consider this key compromised and you do not use it for anything anymore.

**Comment by Kartiiyer12** [comment]
Hi @lnc415 When you mint assets, there is policy script which is used to define conditions for the asset minting. 
The keys you use for policy script is the key to be used for signature to verify that original creator of asset token is registering for asset metadata. 
How was the asset created? Did you had these steps for creating policy - 
https://developers.cardano.org/docs/native-tokens/minting/#minting-native-assets

**Comment by Daawesomedrummer098** [comment]
Yeah I have the policy script and signing key, where do I put it in the
code?

**Comment by Daawesomedrummer098** [comment]
What the fuck?! Why is this shit so hard. The policy is Locked why would it
matter?

**Comment by Daawesomedrummer098** [comment]
Please don't ask me for my correct signing key and then when I provide it,
tell me that I compromised my security and my token is useless now. That
makes no sense

**Comment by Godspeed-exe** [comment]
@Daawesomedrummer098 we never asked you to post your private key here. @Kartiiyer12 asked you to verify that you used the correct key to generate the signatures. Sorry if this was unclear.

As for "why would it matter", anyone can use that private key now to update this registration, change the name, the decimals, the logo, etc. Of course it's your choice if you continue to use this, we can only inform you.

Going back on topic, if you look at the Validate Metadata step of the process it mentions `Failed to parse wallet metadata entry from JSON, error was: Error in $: Couldn't parse verification key:` This means that the key mentioned here is in an incorrect format.

If you have a look at https://github.com/input-output-hk/offchain-metadata-tools/ it contains a metadata generator which will guide you through the steps to generate the correct correct result, including signed values. 
The tools from https://github.com/gitmachtl/scripts/tree/master/cardano/mainnet (step: 12a_genAssetMeta.sh ) 

Does that help?

**Comment by lnc415** [comment]
It does help.  Thank you.  I now know why it is incorrect.
I, myself am still unclear where the public and private keys come from.
I can only assume they are sent out during the token mint, or is the public key generated FROM the private key.
I may attempt to mint my own token and see the results to further help @Daawesomedrummer098 
I hate to waste your time on what I assume is considered very basic things.

Thank you for all your assistance.
I'll be back and probably require more help, so thanks in advance

**Comment by Godspeed-exe** [comment]
Hello @lnc415 

You generate a private key and derive a public key from the private key. Usually from the CLI these are generated in 1 step, which gives you a .skey (secret/private key) and .vkey (verification/public key) file. As the name suggests, 
- a private key has to be kept private at all time, since this is your key to sign and proof ownership.
- a public key can be shared with anyone.

In the token registry: Data is signed with a private key, generates a signature and can be verified with a public key. 

I hope this helps.

**Comment by lnc415** [comment]
@Godspeed-exe yes it helps tremendously.  It seems that step was not taken when creating the file initially.  I have been working through it after the fact and piecing it together.   Thank you again

Now that I have that information, I am at least one step closer 👍

Thank you for taking time to explain, I really do appreciate it

**Comment by Godspeed-exe** [comment]
No worries, happy to help! Good luck!

**Pull request closed without merging**
