### PR TITLE
Request description update for SKILL token

### PR DESCRIPTION
**Pull request by SkillsLabs**
# Pull Request Template

## Description

Requesting update. Just wanting our link added to the tokens description.

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by Godspeed-exe** [comment]
Hey @SkillsLabs 

It seems like the signature of the description attribute has not been updated, although the data has been changed, that's why this verification is failing. Can you update the values and go through the signing process again? Also make sure that you increment the sequence number when you create an update.

Thanks!

**Comment by SkillsLabs** [comment]
Hey @Godspeed-exe, i'm having some issues understand the terminology.

Sorry for any issues.

I'm going to update it again, ill change the description and change the sequenceNumber to 2.

Thankyou!

**Comment by Godspeed-exe** [comment]
Hey @SkillsLabs 

Sorry for the confusion, your last "successfull completed submission" has sequence number 0 ([see here](https://github.com/cardano-foundation/cardano-token-registry/blob/master/mappings/37b03cbc4b1a4fcafc54e70cc31c65b4747a898984c574b3393e003c534b494c4c.json) so  you have to change the sequence number to 1 instead of 2. 

Please have a look at the Details of CI / Validate-Metadata (pull_request_target)  step to see if it makes it through the automated approval. If it's marked with a red X, it failed and the error message should indicate what's going wrong. I still see that it's failing to verify the signature of the description attribute. This needs to be signed by the holder of the policy.skey to make sure it's the actual owner of the policy who is doing these changes. Does that make sense?

**Comment by Godspeed-exe** [comment]
Hi @SkillsLabs 

Closing this because of no response. Feel free to submit a new one / reopen it!

**Pull request closed without merging**
