### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by emctab**
# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [x] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by cleanerm5** [comment]
Hi @emctab 

the CIP-26 off-chain metadata registry is not the place to register CIP-25 compliant NFT metadata (that is usually stored on-chain). Please take a look at our [Wiki](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-to-prepare-an-entry-for-the-registry-%28NA-policy-script%29) where the process to register metadata is described. Also this kind of metadata makes more sense for fungible tokens and not so much non-fungible tokens as the necessary metadata information should actually be stored CIP-25 compliant on-chain with the minting transaction.

Let me know if you need more support on this topic.

**Comment by emctab** [comment]
The token that I am trying to register is fungible, it's not an NFT. It was
made using a website called cardano native token, and can be sent out in
any denomination.

**Comment by cleanerm5** [comment]
Hi @emctab 

understood. But still your metadata is not [CIP-26](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0026) compliant and this is a CIP-26 metadata registry.

**Comment by emctab** [comment]
Ok thank you, I’ll see what I can do!

**Comment by cleanerm5** [comment]
Hey @emctab 

Any support needed with this?

**Comment by cleanerm5** [comment]
I'll close this for now. Come back any time you need it or reach out if you need further support.

**Comment by emctab** [comment]
Thanks!

**Pull request closed without merging**
