### PR TITLE
DigiMart token

### PR DESCRIPTION
**Pull request by Pjb1994-1**
# Pull Request Template

## Description

Update registry
## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Review by Pjb1994-1 — COMMENTED** [review]
Update registry

**Comment by Pjb1994-1** [comment]
Can anyone merge it.

**Review by Pjb1994-1 — COMMENTED** [review]
Review all changes.

**Comment by Pjb1994-1** [comment]
Hey, when I saw my token on cardano token registry

**Review by crptmppt — CHANGES_REQUESTED** [review]
Right now PRs have to be manually processed and have a separate review setup which cannot handle multiple files. Accordingly PRs with more than one mapping file will be closed to prevent overloading the process.
Thank you for resubmitting your mappings as individual PRs for processing (making sure they clear the automated checks!)
(you should not be adding a logo directly in the registry)

**Pull request closed without merging**
