### PR TITLE
Change Logo Metadata

### PR DESCRIPTION
**Pull request by StarsEyeView**
# Pull Request Template

## Replace old json file with new one

Please include a short summary of the changes in this PR.

## Change Logo Image aspect ratio to 1:1

- [ x] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Review by StarsEyeView — COMMENTED** [review]
Change to the Logo Aspect Ration to 1:1.

**Comment by StarsEyeView** [comment]
I just only want to update the logo section of the metadata. Submitting a change with a new json file.

**Comment by cleanerm5** [comment]
There are two files in the PR one ending with a ...(1).json That file must be removed from the PR

**Comment by StarsEyeView** [comment]
I deleted the file with the ...(1).json at the end.

**Review by cleanerm5 — APPROVED** [review]

**Pull request merged**
