### PR TITLE
BaldEagle

### PR DESCRIPTION
**Pull request by jamiebernardin**
# Pull Request Template

## Description

Added metadata for token

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by gitmachtl** [comment]
Is this a test? Token Registry is not opened yet. And your subject must be hex code.

**Comment by jamiebernardin** [comment]
> Is this a test? Token Registry is not opened yet. And your subject must be a hex code.

yeah, i'm just some clueless rando trying to create an NFT on mainnet with metadata.  But don't hate, I love Cardano!!

**Comment by crptmppt** [comment]
Hi @jamiebernardin - the registry service is not live yet, thank you your patience

**Comment by admin-cf** [comment]
Hi jamiebernardin. This service will become live shortly. Please re-submit once we are officially accepting requests. thank you.

**Pull request closed without merging**
