### PR TITLE
Create Mayor_of_Kutztown

### PR DESCRIPTION
**Pull request by G3n3ral-S3ttings**
# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by G3n3ral-S3ttings** [comment]
I would like to publicly state that I have no fucking clue what im doing

**Comment by TrumpFanPool** [comment]
Howdy, you need to follow these instructions https://github.com/cardano-foundation/cardano-token-registry/wiki/How-to-prepare-an-entry-for-the-registry

**Comment by crptmppt** [comment]
This is an empty PR. Thanks for submitting metadata matching a mapping - see the wiki as pointed out, Thanks!

**Review by crptmppt — CHANGES_REQUESTED** [review]
see wiki or portal for how to formulate the mapping file to submit.

**Pull request closed without merging**
