### PR TITLE
Create 338c17dffaaefdb97ace91100724836178c3f9dd994a4798a66f546d4d414e4e59.json

### PR DESCRIPTION
**Pull request by TruthSeeker1987**
…4e59

I am only altering the logo/Image of the preexisting Manny token.  The rest is remaining the same.  I am only changing the base 64 bit for the logo, leaving the rest.  From my understanding, this should work in updating the image.

# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by TruthSeeker1987** [comment]
@VladislavKudrin could you take a look at this revision?  I tagged you in a Git yesterday about how to add a logo.  What are your thoughts here?

**Comment by VladislavKudrin** [comment]
@TruthSeeker1987 
filename should end with .json
mappings/338c17dffaaefdb97ace91100724836178c3f9dd994a4798a66f546d4d414e4e59.json

**Comment by TruthSeeker1987** [comment]
@VladislavKudrin thanks for all your help over the months.  I added the .json to the end.  Let me know if I need to do anything else!  Thanks once again.

**Comment by VladislavKudrin** [comment]
@TruthSeeker1987 you're welcome!

But you've just added .json to the PR tile, file has not been changed. You need to upload the file with .json extension in a new commit

**Comment by TruthSeeker1987** [comment]
@VladislavKudrin thanks for this.  I am trying to create a new commit but it is saying that I already have commits with the same name.  I think I am understanding what needs to be done but need to delete the commits that I have in the Cardano Token Repository before creating a new commit.  Is there anyway you can help me with this process.

Grateful for any help you can offer or any help pointing me in the right direction.  Loving Github but trying to understand the process of things.

**Comment by TruthSeeker1987** [comment]
This is the message I am getting when I try to make a new commit from my fork of the registry.

image

**Pull request closed without merging**
