### PR TITLE
Add a New Client Token by SnekX

### PR DESCRIPTION
**Pull request by CardanoTokenIO**
This is a new token registration request by cardanotoken.io .

### CODE REVIEW

**Comment by Kartiiyer12** [comment]
this cannot be merged as it violates terms of registry

**Comment by TrumpCardano** [comment]
hello, i just want to said you accept the request #5718 (Add a New Client Token by SnekX #5718) that's the same token name, same image and a scam, but refuse our token?? WHY???

**Comment by TrumpCardano** [comment]
i ask you a Recount! Election fraud Sir!

**Comment by TrumpCardano** [comment]
> this cannot be merged as it violates terms of registry

Election Fraud Sir!

**Pull request closed without merging**
