### PR TITLE
Register TEA Token ($TEA)

### PR DESCRIPTION
**Pull request by ReverseBones**
…json

# Pull Request Template

## Description

Adding registration for TEA Token ($TEA).

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by ReverseBones** [comment]
@tienna Hello! Can you help me understand what needs to be fixed please?

**Comment by tienna** [comment]
HI @ReverseBones 
According to the automatic validation, Error in json file

/mappings/7ac1fbdc23238eb2c451d9e5a15bd666f741f8fd951dd54de454bcaf544541.json

You need to prepare this file according to the instructions [here](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-to-prepare-an-entry-for-the-registry-(NA-policy-script))

**Comment by ReverseBones** [comment]
> HI @ReverseBones According to the automatic validation, Error in json file
> 
> /mappings/7ac1fbdc23238eb2c451d9e5a15bd666f741f8fd951dd54de454bcaf544541.json
> 
> You need to prepare this file according to the instructions [here](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-to-prepare-an-entry-for-the-registry-(NA-policy-script))

Hello! I thought we did that. JPGStore gave us [this link](https://github.com/cardano-foundation/cardano-token-registry/commit/d7f2340138706f9afbff6c305f3afd4637e66819) and said to follow it the same way. They recently told me that the image was incorrect, but we used a base64 encoder for it, so it should be okay right? Now sure what we're doing wrong.

**Comment by ReverseBones** [comment]
@tienna I was able to resize the image (I think that was the big issue), so it just needs an "approving review" now--should be good to go now I hope! Thanks for helping!

**Review by tienna — APPROVED** [review]

**Pull request merged**
