### PR TITLE
Add $FIRE and $CHERRY Tokens

### PR DESCRIPTION
**Pull request by phrankerco**
Add $FIRE and $CHERY Tokens to registry

### CODE REVIEW

**Comment by phrankerco** [comment]
was this submitted incorrectly?

**Review by crptmppt — CHANGES_REQUESTED** [review]
Right now PRs have to be manually processed and have a separate review setup which cannot handle multiple files. Accordingly PRs with more than one mapping file will be closed to prevent overloading the process.
Thank you for resubmitting your mappings as individual PRs for processing (making sure they clear the automated checks!)

**Comment by crptmppt** [comment]
> was this submitted incorrectly?

going through the PRs - if you resubmit right away they will be merged today

**Comment by phrankerco** [comment]
attempting to resubmit

**Pull request closed without merging**
