### PR TITLE
DIBS update for decimals

### PR DESCRIPTION
**Pull request by AdaTokenizer**
# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [X] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by d-sfounis** [comment]
I guess if you're trying to update an existing mapping's field, try adding +1 to its sequence number and then resigning the whole thing?

It's probably why validation is failing, based on the logs

**Comment by d-sfounis** [comment]
Your last update was only on the `decimals` attribute, only change that sequence number, not everything, see if that works

**Comment by AdaTokenizer** [comment]
> Your last update was only on the `decimals` attribute, only change that sequence number, not everything, see if that works

Yah, so, I did the sequence number for update, had the json data finalized and re-signed. No changes to anything else, then the validator complained. So I then just pulled the only changing data - for decimals in - and now validator is saying the verification fails for decimals completely.

Ok, I'll make sure to validate locally before next update. One of those mornings already..

**Comment by d-sfounis** [comment]
> > Your last update was only on the `decimals` attribute, only change that sequence number, not everything, see if that works
> 
> Yah, so, I did the sequence number for update, had the json data finalized and re-signed. No changes to anything else, then the validator complained. So I then just pulled the only changing data - for decimals in - and now validator is saying the verification fails for decimals completely.
> 
> Ok, I'll make sure to validate locally before next update. One of those mornings already..

The mapping you're trying to commit looks like a total mess with multiple signatures in fields that have sequence 0.

I know what you mean by it being one of those mornings. Save yourself some headache, reset your fork to `master` and start over, it's a single attribute change anyway

**Comment by AdaTokenizer** [comment]
Closing and will re-do, pre-verify locally.

**Pull request closed without merging**
