### PR TITLE
CHANGE LOGO NIKEP

### PR DESCRIPTION
**Pull request by NikePlushie**
# Pull Request Template

## Description

CHANGE LOGO NIKEP.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by NikePlushie** [comment]
Hi, I tried closing the above and repeating the process! Is the problem resolved? Thanks

**Comment by Kartiiyer12** [comment]
There should be only one file under the mappings folder and not other file as I can there is file outside of the mappings folder as well which is not needed.

Do the same steps that you did last time when you were creating from scratch and just the sequence number and the value for logo that you want to update and submit the PR. Keep the other values are before and submit only one file under mappings folder.

**Comment by NikePlushie** [comment]
> There should be only one file under the mappings folder and not other file as I can there is file outside of the mappings folder as well which is not needed.
> 
> Do the same steps that you did last time when you were creating from scratch and just the sequence number and the value for logo that you want to update and submit the PR. Keep the other values are before and submit only one file under mappings folder.

I don't know how to do it, can you help me? I don't understand what you're saying, this platform has never been used

**Comment by NikePlushie** [comment]
There I deleted and re-uploaded the file

**Comment by Kartiiyer12** [comment]
You wil have to fork this repository again like you did first time for creating the token, update the logo and the sequence number and submit again. The file name would be the same and it will be treated as update and can be merged.
Please read the steps below - 
https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-update-my-entry-in-the-registry

**Pull request closed without merging**
