### PR TITLE
Sharky token

### PR DESCRIPTION
**Pull request by anthonybakx**
# Pull Request Template

## Sharky Token

Creating Sharky Token.

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [x] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by cleanerm5** [comment]
Hi @anthonybakx 

issuing images is not how the token registry is meant to be used. Please see our [Wiki](https://github.com/cardano-foundation/cardano-token-registry/wiki) or [Readme](https://github.com/cardano-foundation/cardano-token-registry#readme) on how to use it and what the actual use case is.

**Comment by anthonybakx** [comment]
I am not trying to issue images. What do I need to do to correct the situation

**Comment by cleanerm5** [comment]
You should follow the instructions at https://github.com/cardano-foundation/cardano-token-registry/wiki/How-to-prepare-an-entry-for-the-registry-%28NA-policy-script%29

If there is any problem. Let me know.

**Comment by cleanerm5** [comment]
Hi @anthonybakx 

could you please remove the JPEG file from the PR. Otherwise the validation will complain about it. If you want to provide an image use the token-metadata-creator for that. It will embed the binary representation of the image as the "logo" property.

The [Wiki](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-to-prepare-an-entry-for-the-registry-%28NA-policy-script%29) has an example for that.
```
token-metadata-creator entry baa836fef09cb35e180fce4b55ded152907af1e2c840ed5218776f2f6d7961737365746e616d65 \
  --ticker "TKN" \
  --url "https://finalfantasy.fandom.com/wiki/Gil" \
  --logo "icon.png" \
  --decimals 4         
```

**Pull request closed without merging**
