### PR TITLE
Update to Ticker and Logo - Earth Token

### PR DESCRIPTION
**Pull request by jaydavies845**
# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

Hello,
The ticker "EARTH" needed to be added to this token metadata. In addition the logo has been updated to show the EARTH Token coin instead of the Unbounded Earth logo which is more appropriate.

Thanks for the info in the last PR 2026. The sequence should now be updated and a new signature should be provided.

FYI - Policy ID: 984394dcc0b08ea12d72b8833292e3c3197d7a8ac89aad61d2f5aa9e URL: https://unbounded.earth/ Twitter: @Unbounded_Earth Original PR: 1923/1936/2026

Many thanks

Jay

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Review by jaydavies845 — COMMENTED** [review]
"sequenceNumber": 0,
        "value": "$EARTH token for use within the Unbounded.Earth metaverse"
        "sequenceNumber": 1,
        "value": "$EARTH token for use within the Unbounded.EArth metaverse"

There is a spelling mistake in the new Description - PLEASE COULD YOU CORRECT IT IF AT ALL POSSIBLE - 'EArth' should be 'Earth'

**Comment by cleanerm5** [comment]
Hi @jaydavies845 

unfortunately I can't because if I change the description without again signing it would render the file as invalid and I cannot do the signing as I do not own the policy signing keys.

**Comment by jaydavies845** [comment]
No problem, is this PR acceptable to be approved? I can then sort out the typo separately if needed! Thanks again really appreciate it

**Comment by cleanerm5** [comment]
Yes. The PR is good to be merged. Just did so ...

**Pull request merged**
