### PR TITLE
STONX token logo update

### PR DESCRIPTION
**Pull request by SimoDod**
# Pull Request Template

## Description

Changing the base64 logo as the last one has a wrong dimensions and looks broken.

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by Godspeed-exe** [comment]
Hello @SimoDod 

The validation is failing because you didn't increment the sequenceNumber value. This needs to be incremented when doing updates. I would point you to this guide: https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-update-my-entry-in-the-registry%3F

Let me know if you have any questions!

**Comment by Godspeed-exe** [comment]
Hello @SimoDod 

Did you also re-sign the updated value? The attestation is failing which makes me believe that the signature wasn't update. Looking at the changes on the file I can also see that the signature isn't changed, while the value is changed, so this needs to be updated.

**Comment by SimoDod** [comment]
Hello @Godspeed-exe 


I've generated the token through a website, streamlining the process significantly. 
As I delved deeper into the details, I cloned the repository and began building the token-metadata-registry. 
Initially, I thought merely adjusting the sequence would suffice, but I've come to realize that signing the data is also necessary.

I will push a new commit once I build the token-metadata-registry with nix and sign the token correctly.

**Comment by Godspeed-exe** [comment]
@SimoDod 

There are simpler ways indeed:
- https://github.com/cardano-foundation/cardano-token-registry/wiki/How-to-prepare-an-entry-for-the-registry-%28NA-policy-script%29 
- I used script 12a_genAssetMeta.sh from this repo in the past https://github.com/gitmachtl/scripts/tree/master/cardano/mainnet
which also uses the token-metadata-creator executable

**Comment by Godspeed-exe** [comment]
@SimoDod still seems to be failing on the signature of the logo.

**Review by Godspeed-exe — APPROVED** [review]

**Pull request merged**
