### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by lekruem**
# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by cleanerm5** [comment]
Hi @lekruem 
The content of this metadata entry does not comply with the terms of use (https://github.com/cardano-foundation/cardano-token-registry/blob/master/Registry_Terms_of_Use.md) in terms of explicit content. I therefore cannot merge it.

**Comment by lekruem** [comment]
Hi @cleanerm5 , thanks for the prompt response! May i know what we should adjust and change in metadata for it to pass compliance?

We're citing this one as a reference: https://github.com/cardano-foundation/cardano-token-registry/pull/1625

**Comment by cleanerm5** [comment]
Hi @lekruem 
I'll merge it then. Wasn't aware of a reference with a similar content that got through a former vetting.

**Review by cleanerm5 — APPROVED** [review]

**Comment by lekruem** [comment]
Thanks @cleanerm5, I appreciate the impartiality. This what Web3 is about, hoping you have a good day ahead of you! 🙏

**Pull request merged**
