### PR TITLE
adding 6 Decimals for accounting

### PR DESCRIPTION
**Pull request by GabrielMazzanti**
# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by cleanerm5** [comment]
Hi @GabrielMazzanti 

do you need any further assistance or clarification on this PR?

**Comment by cleanerm5** [comment]
I am closing this PR as there was no response since a week to my second comment. Feel free to re-issue any time or contact me if any assistance is needed.

**Comment by GabrielMazzanti** [comment]
I'm so sorry, I didn't have time ! Yes I need help I wan't to set 6 decimals on that token ...

**Comment by GabrielMazzanti** [comment]
git hun can be very confusing for new comers

**Comment by cleanerm5** [comment]
Hey @GabrielMazzanti 

no worries and understandable. Best way to do it would be to follow along the instructions provided in the [Wiki](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-update-my-entry-in-the-registry%3F)

If that does not work for you feel free to contact me via E-Mail (address should be in my profile) or Telegram (handle is @cleanerm5) so we can arrange a short call or chat directly.

**Comment by GabrielMazzanti** [comment]
Thank you very much, I'll do that tomorrow :)

**Pull request closed without merging**
