### PR TITLE
GregCoin

### PR DESCRIPTION
**Pull request by gregwhiteman**
# Pull Request Template

## Description

I am adding a new token to the registry

Please include a short summary of the changes in this PR.

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [x] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by cardanative** [comment]
@crptmppt @admin-cf 
again we have a PR that is failing automated checks because of another token.
Is there anyway to fix this?
The same goes for this PR:
https://github.com/cardano-foundation/cardano-token-registry/pull/911

many thanks for your feedbacks.

**Comment by BlackDogeFather** [comment]
> @crptmppt @admin-cf again we have a PR that is failing automated checks because of another token. Is there anyway to fix this? The same goes for this PR: #911
> 
> many thanks for your feedbacks.

Can you explain what the issue is with verification failing due to another coin? I am waiting on approve of #911 and not sure what needs to be done and it’s sort of an urgent update to fix metadata issues for an already registered token…

**Comment by BlackDogeFather** [comment]
Hey Cardano-Foundation/Cardano-Token-Registry Admins!!!

We have been urgently trying to have our metadata update pull request
merged (Pull Request #911, Black Doge is the token) and it seems the auto
check failed for some reason and we have checked the accuracy and format of
the submission over and over again, and everything appears to be done
correctly.

Again, this is pull request is #911 for Black Doge ... Is there any way you
could please look into this issue for us as soon as you have a chance? We
have a loyal community of holders and the longer this issue persists the
more our credibility is suffering. Anything we can do to help expedite the
merging of the corrected metadata submitted would be so very much
appreciated, you really have no idea how much it would mean to us! If you
could assist I would be forever grateful to you guys!!

Please take a look and let us know if there is any further action which
must be done on our part.

THANK YOU SO MUCH!!!

Best regards,
Matt

**Comment by crptmppt** [comment]
Hi Greg - apologies for the delay due to holidays - this PR is touching multiple files and appears closed right now.. If you are trying to change an existing mapping, please refer to the wiki for specific steps. WIll go through the backlog again this Monday and processing will resume as normal soon, thank you for your patience!

**Pull request closed without merging**
