### PR TITLE
GHOST has no decimals

### PR DESCRIPTION
**Pull request by SaIG**
# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by cleanerm5** [comment]
Hi @SaIG 

You need to increment the sequence number of the decimala property by one to have the validation pass.

**Comment by SaIG** [comment]
GHOST has no decimals

**Comment by SaIG** [comment]
Changed decimals

**Comment by SaIG** [comment]
GHOST

**Comment by SaIG** [comment]
I have now increased sequence of every entry by 1 because the validation threw lots of errors regarding this. 
Valdiation now says something about wallet .. 
"  [Main.log#276] Failed to validate wallet metadata entry, error was: 'attestation verification failed for: name'."
What can be done here?

**Comment by SaIG** [comment]
Metadata check seems  to always fail ... Updated the file step by step like the wiki said ... but i didnt hade to increment the sequence number manually it did it by it self

**Comment by SaIG** [comment]
> @SaIG would you mind doing a video call on that to sort things out? Just drop me a mail and I schedule a meeting for us.

thx dropped you an email !

**Review by cleanerm5 — APPROVED** [review]

**Pull request merged**
