### PR TITLE
Updating MANNY

### PR DESCRIPTION
**Pull request by TruthSeeker1987**
…4e59.json

Updated the base 64 bit metadata for the logo. 

# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by TruthSeeker1987** [comment]
@tienna I hope all is well.  Is there anyway that you could help me by reviewing this PR?  I would greatly appreciate it.  Blessings.

**Comment by iMomento** [comment]
Hi bro. I'm very new to these stuff but I think it now that its the second time you've updated the logo you need to change the sequence to 1. I maybe wrong but I just wanted to give u something to try as ive seen you here with no help for a couple of days. and also make sure your logo is 64 by 64 pixels and under 10kb.

**Comment by TruthSeeker1987** [comment]
Hey @iMoment!!  Thanks for sending your thoughts!  They are appreciated.  I'm gonna work on seeing if the 64 by 64 pixel change helps.  Not sure about the sequence number but I may try changing that too if it still isn't working after altering the pixel count.  Again, grateful, thx!!

**Comment by TruthSeeker1987** [comment]
Okay.  I seem to have made progress (thanks @iMomento).  But it seems it still needs something.

**Comment by TruthSeeker1987** [comment]
Hello @cardano-foundation,

I hope all is well.  I'm trying to figure out why this isn't going though.  Is there anyway that you can aid in this process?

Blessings,

Sidenote: Cessna 172?  Love the plane

**Comment by iMomento** [comment]
Hi Pal, good to hear youve made some progress. when I decode your logo it comes to 117KB. keep trying a smaller size every time. I did 64 x 64 for my logo which came down to like 5kb. If youve already put a high quality version of your logo on the metadata when you did it on chain then you can just use a much smaller logo size for this metadata (off-chain) and it will show both depending on the platform.

**Comment by TruthSeeker1987** [comment]
@iMomento and @tienna.  I have updated the logo again.  This time it has been reduced to about 50 kbs.  It should work right?  I would go smaller but would like the logo visible in people's cardano wallets.  That being said it is still not working.  Let me know your thoughts.  Blessings

**Comment by TruthSeeker1987** [comment]
@iMomento, @tienna, @VladislavKudrin, @cardano-foundation,

I am seeing this are pop up when it runs the validator.  Any ideas on why it is not executing?  Thanks in advance for any help.

image

**Comment by iMomento** [comment]
Hi hope youre well, I think the policyID above the logo is the problem, just remove it and it should work.

**Review by tienna — APPROVED** [review]

**Comment by TruthSeeker1987** [comment]
Any idea why the logo hasn't loaded in on chain.  You were right @iMomento, it went through but it says that it should take four hours to show on chain.  Now it's going on 8ish hours.  Any idea why? Or if there is something else.  Should I have changed the sequence number to 2?  Thanks for all of your help on this.  I am beyond grateful.

**Comment by TruthSeeker1987** [comment]
Actually seeing that it is changed on pool.pm but it isn't changed on different Cardano plateforms like taptools (etc)

**Comment by TruthSeeker1987** [comment]
Hey @tienna and @iMomento .  Hope all is well.  Any idea why the token image isn't being updated in the token metadata.  It changed in pool.pm and in minswap but not in places like the etrnel wallet.

Also, I not cannot find the token on the wingriders and sundaeswap dexs.  Any idea why?

**Pull request merged**
