### PR TITLE
$fakeADA registration for testing decimals

### PR DESCRIPTION
**Pull request by zwilling**
# Pull Request Template

## Description

$fakeADA registration for testing decimals

## Type of change

- [x] Metadata related change

## Checklist:

- [x] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by Kartiiyer12** [comment]
Hi @zwilling The asset name "FADA" impersonates name of "ADA" and could not be merged. I am checking for FUSD as well.

**Comment by badasserry** [comment]
It's for fathom usd

**Comment by zwilling** [comment]
Thanks for the feedback. I will change the name then.

**Review by badasserry — COMMENTED** [review]
FADA Father's And Dad's Asset

**Pull request closed without merging**
