### PR TITLE
WorldCoin Adding 

### PR DESCRIPTION
**Pull request by GabrielMazzanti**
Use of New "ProNFT Token" account

# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Review by crptmppt — CHANGES_REQUESTED** [review]
Right now PRs have to be manually processed and have a separate review setup which cannot handle multiple files. Accordingly PRs with more than one mapping file will be closed to prevent overloading the process.
Thank you for resubmitting your mappings as individual PRs for processing (making sure they clear the automated checks!)

**Comment by crptmppt** [comment]
The PR is still showing two files - Consider closing this PR and submitting two new ones for process, or it might be closed in the coming weeks.

**Comment by GabrielMazzanti** [comment]
Hey, Just one this time (i'm very bad at github...)

**Comment by crptmppt** [comment]
@GabrielMazzanti - the PR still shows the back and forth and displays 4 files being touched - consider closing this PR, and submitting a new one, with just the file you want to add/submit added!

**Pull request closed without merging**
