### PR TITLE
Create f0ff48bbb7bbe9d59a40f1ce90e9e9d0ff5002ec48f232b49ca0fb9a.json

### PR DESCRIPTION
**Pull request by JDR1950**
{
  "721": {
    "f0ff48bbb7bbe9d59a40f1ce90e9e9d0ff5002ec48f232b49ca0fb9a": {
      "706561636525323066757475726500": {
        "name": "Peace Future Token",
        "description": "A token promoting peace and a better future.",
        "ticker": "PFT",
        "url": "https://peacefuture.com",
        "logo": "QmAbCdEfGhIjKlMnOpQrStUvWxYz1234567890",
        "decimals": 0
      }
    }
  }
}

# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by VladislavKudrin** [comment]
Hi @JDR1950,

you submitted an empty json 
Please update the PR

Thanks!

**Comment by JDR1950** [comment]
This is what I was trying to create:{  "721": {    "f0ff48bbb7bbe9d59a40f1ce90e9e9d0ff5002ec48f232b49ca0fb9a": {      "706561636525323066757475726500": {        "name": "Peace Future Token",        "description": "A token promoting peace and a better future.",        "ticker": "PFT",        "url": "https://peacefuture.com",        "logo": "QmAbCdEfGhIjKlMnOpQrStUvWxYz1234567890",        "decimals": 0      }    }  }}On Apr 17, 2024, at 7:14 AM, VladislavKudrin ***@***.***> wrote:﻿
Hi @JDR1950,
you submitted an empty json
Please update the PR
Thanks!

**Comment by JDR1950** [comment]
{
  "721": {
    "f0ff48bbb7bbe9d59a40f1ce90e9e9d0ff5002ec48f232b49ca0fb9a": {
      "706561636525323066757475726500": {
        "name": "Peace Future Token",
        "description": "A token promoting peace and a better future.",
        "ticker": "PFT",
        "url": "https://peacefuture.com",
        "logo": "QmAbCdEfGhIjKlMnOpQrStUvWxYz1234567890",
        "decimals": 0
      }
    }
  }
}

**Comment by VladislavKudrin** [comment]
@JDR1950 
You should follow the [guide](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-to-prepare-an-entry-for-the-registry-%28NA-policy-script%29) to create the submission. 
You can also make yourself comfortable with token-metadata-creator by watching this [video](https://www.youtube.com/watch?v=lZBGTY_luzo&t=589s&ab_channel=%5BMnM%5DMinimumFeeCharityPool-Cardano)

Please update the PR

**Comment by VladislavKudrin** [comment]
Closed due to inactivity

**Pull request closed without merging**
