### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by cardanodo**
# NODO Tokens Pull Request

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [x] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Review by crptmppt — CHANGES_REQUESTED** [review]
Your PR currently adds a metadata field that isn’t part of the well-known properties. 
There is work ongoing to support checks to additional fields, but for right now your PR is going to be held back until either 
you remove the “tool” field, 
or 
the supporting of additional fields and associated checks gets implemented at a future time.

Thank you for your patience!

**Comment by cardanodo** [comment]
Hi Frederic,

Thanks for reviewing our pull request. We have removed the "tool" field. 

Could you please kindly take a look at your convenience?

Sincerely,
Cardanodo Team

**Comment by cardanodo** [comment]
> Your PR currently adds a metadata field that isn’t part of the well-known properties.
> There is work ongoing to support checks to additional fields, but for right now your PR is going to be held back until either
> you remove the “tool” field,
> or
> the supporting of additional fields and associated checks gets implemented at a future time.
> 
> Thank you for your patience!

**Review by crptmppt — CHANGES_REQUESTED** [review]
The PR is failling the Automated Checks. This seems to be due to CI changes pushed post-PR in CI.yaml.
Rebasing the PR should solve the issue - but if it persists it might be simpler to close this one and re-open a new one - Thanks for your understanding.

**Pull request closed without merging**
