### PR TITLE
World of Warriors

### PR DESCRIPTION
**Pull request by apolaki85**
# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by cleanerm5** [comment]
Hi @apolaki85 

this will not work. You copied the commands from the instructions in files but in the end we need the output generated by those commands and as you only know the values that shall be in the metadata and own the keys to sign it we cannot generate it for you based on the commands. You can follow the instructions in our Wiki on [How to create metadata files](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-to-prepare-an-entry-for-the-registry-%28NA-policy-script%29) and [How to submit metadata files](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-to-submit-an-entry-to-the-registry).

If that does not work for you and you need any assistance contact me directly and we try to solve it together.

**Comment by apolaki85** [comment]
Okay thank. I’m working on your instructions please bare with me

**Comment by cleanerm5** [comment]
Hi @apolaki85 

you are still working on it? Let me know if you need further assistance or send me an E-Mail so we can find a slot to do a call to sort things out.

**Comment by cleanerm5** [comment]
10 days have passed since last activity. I'll close this PR. Feel free to re-issue if needed.

**Pull request closed without merging**
