### PR TITLE
One Time Minter Prod

### PR DESCRIPTION
**Pull request by odedNea**
# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by Godspeed-exe** [comment]
**Automated feedback**<br /><br />**Value:** <br />please check files manually<br /><br />**Attribute:** <br />logo<br /><br />**Analysis:** <br />The image depicts a cartoon character, who is recognizable as Ash Ketchum, a character from the Pokémon franchise.<br /><br />

**Comment by odedNea** [comment]
Hi, please let me know if I should change the logo

**Review by linconvidal — CHANGES_REQUESTED** [review]
Hi @odedNea,

Please update the logo in your submission as it includes copyrighted material, which is not allowed according to the [Terms of Use](https://github.com/cardano-foundation/cardano-token-registry/blob/master/Registry_Terms_of_Use.md).

> The User shall not submit information that infringes another party’s rights, including but not limited to: Information containing content protected by intellectual property rights, e.g. copyrights, trademarks, patents.

Thank you for your cooperation and understanding.

**Comment by odedNea** [comment]
Thanks for checking @linconvidal 
I've updated the logo.

**Review by linconvidal — APPROVED** [review]

**Pull request merged**
