### PR TITLE
Update World Mobile Token metadata

### PR DESCRIPTION
**Pull request by Eloi**
Update subject to properly match minted asset

# Pull Request Template

## Description

Update World Mobile Token metadata subject

Here it is the minted token on Cardanoscan: 
https://cardanoscan.io/token/1d7f33bd23d85e1a25d87d86fac4f199c3197a2f7afeb662a0f34e1e776f726c646d6f62696c65746f6b656e

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Review by crptmppt — CHANGES_REQUESTED** [review]
Please ensure a singular signature (currently has two per field)

**Comment by Eloi** [comment]
> Please ensure a singular signature (currently has two per field)

The policy of this asset requires two signatures for the minting of tokens. AFAIK, the metadata has to follow the same rules than the asset policy, except the time-lock related restrictions to mint/burn tokens. 

In any case, the token-metadata-creator tool is following this rules. If I provide one one signature on one field, e.g. the url, I get the following error when trying to finalze the metadata

```
token-metadata-creator entry 1d7f33bd23d85e1a25d87d86fac4f199c3197a2f7afeb662a0f34e1e576f726c64204d6f62696c6520546f6b656e --finalize
Finalizing: policy evaluation failed for: url
Policy is:
(AllOf
   (Signature
      (KeyHash #"1423d22ea96d09b88162b1b7a9a88df1bfc2aec37cd805428d6a0d33"))
   (Signature
      (KeyHash #"4c0b87c21190ad6f6144d0609761a8af515efd3fabcc8d929d63e9e3"))
   (Expires SlotNo 33505253)
````
The tool only considers the metadata valid, if both keys sign all the fields.

So, could you please reconsider your request, and approve the PR?

**Comment by crptmppt** [comment]
This might be beyond the current scope of the registry - for right now the expected format is outlined and explained in the Registry wiki - future functionalities might extend to other type of tokens, for the current iteration the focuses is on coin-like tokens with simple policies (although not spelled out). Leaving the PR open, flagging for discussion.

**Comment by Eloi** [comment]
Sorry, but I don't understand your concerns. Its a very simple policy, perfectly supported by your own cardano-metadata-creator tool. 

Also, another PR we did for some metadata with exactly the same policy than this PR, was merged last week: https://github.com/cardano-foundation/cardano-token-registry/pull/214

Could you please clarify this? Pinging @admin-cf that merged the other PR to bring some light into this issue.

**Comment by crptmppt** [comment]
Tool (metadata-creator) and the instance of the registry are separate: the Foundation has a more narrow acceptance criteria as noted in prior comments, post and wiki.  Because we do a lot (most) of the checking/vetting manually, we limit mappings to the more simpler one - will review the other one accordingly and discuss internally - thank you for understanding!

**Comment by Eloi** [comment]
Sorry for being insistent, but apart from our own PR with a multisignature policy being merged last week,  you accepted last month another PR that adds a multisignature metadata:

https://github.com/cardano-foundation/cardano-token-registry/pull/171

So, again I would kindly request for you to accept this PR, or at least reach to @admin-cf to discuss the criteria you use to accept PRs with multisignature, and let us know if we need to update our PR in any way.
 
If you want I'm happy to remove one of the signatures and resubmit again the metadata, but any tool that checks the metadata validity against the policy will fail, so I don't think that its the appropriate thing to do.

**Comment by Eloi** [comment]
In relation to this issue, I've reviewed the newest documentation to see if there was a mention about some restriction on the number of keys in the policy.

In any case, the opposite is true. Its mentioned in several places that you need your key/s to sign the metadata, and that all the signers of the policy are required for the metadata to be accepted. E.g. see:

https://github.com/cardano-foundation/cardano-token-registry/wiki/How-to-prepare-an-entry-for-the-registry#step-5-sign-your-metadata

**Comment by crptmppt** [comment]
Thanks for your patience as we review the issue in the coming days!

**Comment by crptmppt** [comment]
Hi @Eloi - still looking into the matter with @admin-cf. 
Meanwhile, this (223) is a concurrent **new** mapping with same policyID as https://github.com/cardano-foundation/cardano-token-registry/pull/214 
(it isn't "Updating") 
=> Could you submit a PR to delete the prior (offending) mapping to prevent conflicting scenarios? See [wiki](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-delete-my-entry-from-the-registry%3F) / need to change name to VOID and we can delete the mapping file accordingly.

**Comment by Eloi** [comment]
Thanks for your support.

As requested, here it is the PR to invalidate the previous metadata, following the procedure described in the wiki: https://github.com/cardano-foundation/cardano-token-registry/pull/226

**Comment by Eloi** [comment]
Thanks for merging https://github.com/cardano-foundation/cardano-token-registry/pull/226.

I've updated this PR to only add the single commit introducing the new metadata, so is ready to be merged when gets approved.

**Review by crptmppt — APPROVED** [review]

**Comment by ben221199** [comment]
We have a same problem in #2698: `Failed to validate wallet metadata entry, error was: 'policy evaluation failed for: name`.

**Pull request merged**
