### PR TITLE
CHIPS

### PR DESCRIPTION
**Pull request by cunni57005**
# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by Godspeed-exe** [comment]
Hello @cunni57005 

Is it correct that you want to register 4 assets with almost the same name and the same logo? Or did you make a mistake somewhere during minting?

**Comment by cunni57005** [comment]
Oops.  Sorry about that.  [87eb55b] and [2be8991] are meant to be committed.  The other two can be ignored.

**Comment by cunni57005** [comment]
2 separate tokens.  8991 is 500MM and b55b is 100MM.  I will change the logo for one once registered.  Thanks.

**Comment by Godspeed-exe** [comment]
@cunni57005 can you remove the ones that “can be ignored”? No use in merging if they aren’t needed. Thanks!

**Pull request closed without merging**
