### PR TITLE
CardanoBits

### PR DESCRIPTION
**Pull request by cardanobits**
Adding CardanoBits

### CODE REVIEW

**Comment by mmahut** [comment]
This is not how it works. You need to assign the metadata to a token, not the entire policy.

**Comment by ashisherc** [comment]
We should have a standard to add metadata for the policy for NFT projects. If we decide to follow this pattern, it clashes with a token with NO AssetName.

**Comment by cardanobits** [comment]
Hi there! Ok, I uploaded this way, since each NFT has a different assetname (CardanoBits0, CardanoBits1, etc). Which should be the way then?

**Review by admin-cf — APPROVED** [review]

**Comment by crptmppt** [comment]
@admin-cf  -This cleared the tests but is trying to register the policy rather than the tokens. Reverting to let user fix/adjust.

**Pull request merged**
