### PR TITLE
Create TICKET Token

### PR DESCRIPTION
**Pull request by curtindoavida**
# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [x] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by curtindoavida** [comment]
Do I need to do anything else?

**Comment by cleanerm5** [comment]
Hi @curtindoavida 

how did you do the token minting? Via monetary policy script (e.g. like described [here](https://developers.cardano.org/docs/native-tokens/minting/)) or smart contract based?

**Comment by curtindoavida** [comment]
By smart contract ( https://cardano-native-token.com/ ). The policy is locked now and all information about this token is possible to see into https://rafflesocial.com/tokenomics

**Comment by cleanerm5** [comment]
Thanks for the clarification.

**Review by cleanerm5 — APPROVED** [review]

**Pull request merged**
