### PR TITLE
Update token_config.json: Supply to 21M, Name/Symbol Change

### PR DESCRIPTION
**Pull request by MemeBTC21**
Description
This PR addresses a previous error in token configuration and slightly modifies the token's name and symbol:

Total Supply Correction: Updated token_config.json to reflect the intended total supply of 21 million. The previous incorrect value was 2,100,000.
Name and Symbol Update:
Token Name: MEMEBTC
Symbol: MemeBTC
Fingerprint: asset1u2yk6waz2kh3zdv4k8jtlj8kdjv2n3yd7xuhk2
Policy ID: 0d9830b76451561f5c6503b489aa9f29768a1501c30b6baefefb57ec
Asset Name: 4d656d65425443
Type of change
[x] Metadata related change
[ ] Other
Checklist:
[x] For metadata related changes, this PR code passes the GitHub Actions metadata validation
Metadata PRs
Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

Explanation:

Clarity: The description summarizes the errors encountered and the specific changes made.
Metadata Detail: All important metadata elements are included for complete transparency.

### CODE REVIEW

**Review by MemeBTC21 — COMMENTED** [review]
Update Token Supply to 21 Million (previously set at 2,100,000 in error)

**Comment by VladislavKudrin** [comment]
Hi @MemeBTC21,

1. Remove the file from root folder, so that only the one in the mappings folder remains.
2. Follow this guide to update values [How to update my entry](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-update-my-entry-in-the-registry%3F)

Thanks!

**Review by MemeBTC21 — COMMENTED** [review]
Duplicate file removed

**Review by MemeBTC21 — COMMENTED** [review]
Resubmitting Jason file again to fix the error

**Comment by MemeBTC21** [comment]
> Hi @MemeBTC21,
> 
> Remove the file from root folder, so that only the one in the mappings folder remains.
> 
> Thanks!

Hi, thanks very much for your patience. I hope this will fix the problem finally.
Regards

**Review by VladislavKudrin — APPROVED** [review]

**Comment by MemeBTC21** [comment]
Thank you very much my friend. I appreciate your help.
Great service
Regards

**Pull request merged**
