### PR TITLE
Adding SAD token to registry 

### PR DESCRIPTION
**Pull request by iMomento**

### CODE REVIEW

**Comment by iMomento** [comment]
Hello, Please can someone help me with this. ive tried manu different ways but not been successful. Highly appreciate it.

**Comment by iMomento** [comment]
@tienna Hi there, hope all is well, please can you see whats wrong with this, ive tried everything I could but no success. highly appreciate it.

**Comment by iMomento** [comment]
@theeldermillenial hi there , hope youre well, is there any chance u could help me with this, ive already registered on chain but for some reason when i try register here i keep getting error, would highly appreciate your help, thanks

**Comment by theeldermillenial** [comment]
@iMomento Unfortunately I'm strapped for time. If you wanted to contract me to look and debug this, I'd be happy to. I usually like to try and help people out, I'm just under water working on things with all the current chain activity.

**Comment by iMomento** [comment]
@theeldermillenial no worries thank you for getting back to me i appreciate it

**Pull request closed without merging**
