### PR TITLE
Update MOAI Token

### PR DESCRIPTION
**Pull request by moaipool**
# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [x] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by cleanerm5** [comment]
Hi @moaipool 

you must also increment the "sequenceNumber" of the property that is modified by 1 and afterwards sign the document again. Otherwise the validation fails.

**Comment by moaipool** [comment]
@cleanerm5 got it. updated, signed + validated, thanks

**Comment by cleanerm5** [comment]
Hi @moaipool 

it looks like you were trying to update and sign the already finalized file again. This does not work. You need to update the draft file and then sign it again. Otherwise the signature part is double inserted/appended.

**Comment by moaipool** [comment]
Hmm ok. `token-metadata-creator validate` returned "validation successful" so assumed it was in good shape. 
The original draft no longer exists, so should we delete the original mapping and create a new PR?

**Comment by cleanerm5** [comment]
Hi @moaipool 

the file is valid now on its own. Only issue left is that it updates some properties without having the sequenceNumber incremented of those properties. So what you need to do is to set the sequenceNumber of the logo property to 1 in the "draft" file and sign and finalize the file again.

Sorry for the long journey. If that does not work just drop me an E-Mail and let's have a short call on it to sort this out together to not longer waste your time with it.

**Comment by moaipool** [comment]
This one passed the CI check finally. Appreciate the tips.
There's no mention of updating the sequenceNumber in the readme. Might be an idea to include some verbiage to this effect.

**Review by cleanerm5 — APPROVED** [review]

**Pull request merged**
