### PR TITLE
CHICOIN

### PR DESCRIPTION
**Pull request by petloverstake**
# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Review by petloverstake — COMMENTED** [review]
Needing to delete ...316.json file. The right one is ...94e.json

**Comment by cleanerm5** [comment]
Hi @petloverstake 

direct deletions of files are not allowed. If you want to delete a metadata file you need to follow the instructions provided in the [Wiki](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-delete-my-entry-from-the-registry%3F).

I propose to split the PR (one for adding the new file and one for the deletion).

**Review by petloverstake — COMMENTED** [review]
Hi, I did the split, now shows the first file for metadata registration and the second one marked for deletion. Sorry, I'm still learning the whole process, thanks for your time.

**Review by petloverstake — COMMENTED** [review]
I need to do something else?

**Comment by cleanerm5** [comment]
The validation fails on deleted files. You have two options:
1. Change the "deletion" to a modification of the file that shall be deleted according to the instructions provided in the [Wiki](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-delete-my-entry-from-the-registry%3F).
2. Change this PR and remove the change that deletes the second file. Then the validation should probably run through for the added file and I can merge the new data. After that create a second file that contains the changes for the file you want to delete from the registry according to the Wiki instruction.

**Comment by cleanerm5** [comment]
This looks almost correct. Only part missing for the updates file is that you need to increment the sequence number before signing.

**Review by petloverstake — COMMENTED** [review]
sequenceNumber : 1

**Comment by petloverstake** [comment]
> This looks almost correct. Only part missing for the updates file is that you need to increment the sequence number before signing.

Hi cleanerm5, I did the sequenceNumber++,  but looks like don't work either, now said invalid file name:
[Error]   [Main.log#276] Metadata subject 'be18c25cdb2dbe713131a313d257456664d0f3bc9fc316fd256fcf2f43415444414e4f', does not match file name 'be18c25cdb2dbe713131a313d257456664d0f3bc9fc316fd256fcf2fbe18c25cdb2dbe713131a313d257456664d0f3bc9fc316'

That long name was my first mistake, then I tried to fix it and the current file name  CATDANO json file is now:
(be18c25cdb2dbe713131a313d257456664d0f3bc9fc316fd256fcf2f43415444414e4f.json).  In case CATDANO's one can't proceed, then is it some chance to update metadata for CHICOIN only? thanks...

**Comment by cleanerm5** [comment]
Hi @petloverstake 

would you please drop me an E-Mail that we can arrange a chat? Guess it takes too much back and forth via Github comments.

Kind regards

**Comment by petloverstake** [comment]
> Hi @petloverstake
> 
> would you please drop me an E-Mail that we can arrange a chat? Guess it takes too much back and forth via Github comments.
> 
> Kind regards

Hello @cleanerm5, of course: petloverstake@gmail.com
Thanks!

**Comment by cleanerm5** [comment]
#1878 
#1880

**Pull request closed without merging**
