### PR TITLE
Create PAVIA Token

### PR DESCRIPTION
**Pull request by sp33dy**
PAVIA's Metaverse token

# Pull Request Template

The first registration of the PAVIA's Metaverse token.

## Type of change

- [ * ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by sp33dy** [comment]
I forgot to say, I'm the VEGAS Pool operator. You can always reach me on telegram at: https://t.me/VEGAS_ADA_POOL

**Comment by sp33dy** [comment]
I've now committed HOSKY too.

**Comment by sp33dy** [comment]
Now added Kidz Coin too.

**Comment by ggcaponetto** [comment]
Hi @sp33dy I am almost sure that every coin needs it's own PR.

**Comment by sp33dy** [comment]
> Hi @sp33dy I am almost sure that every coin needs its own PR.

Oh really? This is where I lack the github experience. I creating the original PR, then worked on the other two coin's and committed them. They then got added to this PR. Is there a way to separate them out? Github didn't give me a way to create them as separate PR's??

**Comment by sp33dy** [comment]
Having googled.. I need to create a separate fork for each pull request. Can someone advise what to do here? Do I close this entired, or do I delete the other two file commits? Happy to conform, but need to know what you'd like me to do.

**Comment by sp33dy** [comment]
I can't seperate these out, because GitHub wont allow me to make multiple forks of the repository. What is the advice here?

**Comment by cardano-tools-nft** [comment]
Create dedicated branches for each token in you repository, and make dedicated pull requests for each. Of course the branches should not depend on each other.

**Comment by cardano-tools-nft** [comment]
2022-01-20 20_37_32-C__github_cardano-token-registry-tools - Log Messages - TortoiseGit

**Comment by sp33dy** [comment]
Thanks. I'll close this and try again.

**Pull request closed without merging**
