### PR TITLE
Create WorldCoin

### PR DESCRIPTION
**Pull request by GabrielMazzanti**
@GabrielMazzant3 

Twitter

# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by GabrielMazzanti** [comment]
Hey I just posted on my @GabrielMazzant3 Twitter account the link to this pull request

**Comment by GabrielMazzanti** [comment]
I'm off to see the wizard, sorry my boss

**Comment by GabrielMazzanti** [comment]
Hey, GitHUb community, can someone tell me what I have to change ? this was the original Json given by Cardano mint... Maybe do you want the real json ?

**Comment by cleanerm5** [comment]
Superseded by #1250

**Comment by GabrielMazzanti** [comment]
oki thanks i'll delete everything and start again

**Pull request closed without merging**
