### PR TITLE
Petloverstake newtokens

### PR DESCRIPTION
**Pull request by petloverstake**
# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Review by petloverstake — COMMENTED** [review]
Two new tokens under the policy: be18c25cdb2dbe713131a313d257456664d0f3bc9fc316fd256fcf2f (ADAKOI and PETBIRD) files: be18c25cdb2dbe713131a313d257456664d0f3bc9fc316fd256fcf2f4144414b4f49.json and be18c25cdb2dbe713131a313d257456664d0f3bc9fc316fd256fcf2f50455442495244.json

**Comment by cleanerm5** [comment]
Hi @petloverstake 

this branch conflicts with the master branch. Please resolve the conflicts before issuing the pull request. Perhaps you did not fork from the latest head of the master branch?

**Comment by petloverstake** [comment]
closing the PR, I will open it again

**Comment by petloverstake** [comment]
Hello, Sebastian

Yes, looks like I used the conflictive old fork.
I deleted it and created the PR again (PETBIRD and ADAKOI PETokens
<https://github.com/cardano-foundation/cardano-token-registry/pull/2113>),
please let me know if it's ok.
Thanks!
Leo.

**Pull request closed without merging**
