### PR TITLE
WENMINT Podcast WEN token submission

### PR DESCRIPTION
**Pull request by NFTMachinist**
# Pull Request Template

## Description

Registration Request For WENMINT Podcasts WEN Token 
## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by NFTMachinist** [comment]
This is my first time requesting a token submission. If anything needs to be done differently, please reach out! Thank you for your time.

_-NFTMachinist_

**Comment by NFTMachinist** [comment]
Thank you for reaching out!

I didn’t realize the decimal wasn’t added on to the number. I’ll probably
go with 0 then. Should I resubmit the json file with the updated info?

**Comment by Kartiiyer12** [comment]
Yes, you can change the value and submit again.

**Comment by NFTMachinist** [comment]
Thank you, I will do that.

**Review by Kartiiyer12 — APPROVED** [review]

**Pull request merged**
