### PR TITLE
Nike Plushie NIKEP Change logo

### PR DESCRIPTION
**Pull request by NikePlushie**
# Pull Request Template

## Description

Nike Plushie NIKEP Change logo .

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by NikePlushie** [comment]
Hello! I need to change the logo, it was registered with a very low quality logo and I was able to make a new one, but I don't really understand any of this, I don't know what this conflict means and how to solve it, could you help me? I did the whole previous process again, I don't know if that solves it, thanks

**Review by Kartiiyer12 — APPROVED** [review]

**Comment by Kartiiyer12** [comment]
Hi @NikePlushie 
As you do not have the recent master branch, this is causing problems in merging.
For updating,

- Pull recent master branch instead of using the older branch you have cloned.
- Make changes to his fork
- Commit

Please read through the wiki for more information - 
https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-update-my-entry-in-the-registry

**Comment by NikePlushie** [comment]
> Hi @NikePlushie As you do not have the recent master branch, this is causing problems in merging. For updating,
> 
> * Pull recent master branch instead of using the older branch you have cloned.
> * Make changes to his fork
> * Commit
> 
> Please read through the wiki for more information - https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-update-my-entry-in-the-registry

Hi! I couldn't do it, I don't know how you can help me?

**Comment by NikePlushie** [comment]
I tried again but I couldn't.

**Pull request closed without merging**
