### PR TITLE
Update $FAM Token

### PR DESCRIPTION
**Pull request by MrPantsGoesToFargo**
# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by MrPantsGoesToFargo** [comment]
I am sorry for having a couple of close succession Pull Requests, I think this one should work.

**Comment by Godspeed-exe** [comment]
@MrPantsGoesToFargo the decimal value has changed since you signed it, so this means that signature doesn’t match the value and doesn’t pass validation.

can you go through the signing process again? Thanks

**Comment by MrPantsGoesToFargo** [comment]
Sure thing, I will take care of that and double check the JSON before I try another pull request.

**Comment by MrPantsGoesToFargo** [comment]
@Godspeed-exe We redid the JSON from scratch, thank you for the notes and I hope this one works. Thank you for your time.

**Review by Godspeed-exe — APPROVED** [review]

**Pull request merged**
