### PR TITLE
Terrible Cake Party

### PR DESCRIPTION
**Pull request by Terrible-Cake-Party**
# Pull Request Template

## Description

Update token logo image to new image. 

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by Terrible-Cake-Party** [comment]
Is it possible to get a explanation of what's wrong in the metadata that's causing it to not be validated (I know its related to the image encoding, maybe the line is too long or its the wrong format or something)? Thanks.

**Comment by Terrible-Cake-Party** [comment]
Metadata error in request: [a7482c0]
Fixed with request: [a655bcc]

**Comment by tienna** [comment]
> Metadata error in request: [[a7482c0](https://github.com/cardano-foundation/cardano-token-registry/commit/a7482c0306c1253384ffdc131fa6510bf65d2eea)] Fixed with request: [[a655bcc](https://github.com/cardano-foundation/cardano-token-registry/commit/a655bccace755b238037369623f8eb4ec3ded3e1)]

Hi @Terrible-Cake-Party 
Please follow [this instruction](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-update-my-entry-in-the-registry%3F) to update your request

**Comment by tienna** [comment]
We closed this request because there was no further interaction from the user.

**Pull request closed without merging**
