### PR TITLE
Update 9b426921a21f54600711da0be1a12b026703a9bd8eb9848d08c9d921434154…

### PR DESCRIPTION
**Pull request by ThaMacroMan**
…534b59.json

Update Logo, Description, And name from Catsky to Catsky AI

# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by ThaMacroMan** [comment]
I am not sure whats wrong. Thinking its something to do with the logo Base64 - but not sure what.

**Comment by Godspeed-exe** [comment]
Hello @ThaMacroMan 

At the end of line 56 after `and services."` you are missing , 

The Base64 of the image also seems a bit weird, normally this starts with `iVBO`. I would suggest to reconvert it with a tool like: https://base64.guru/converter/encode/image

Let me know how it works!

Enjoy your day!

**Comment by ThaMacroMan** [comment]
> Hello @ThaMacroMan
> 
> At the end of line 56 after `and services."` you are missing ,
> 
> The Base64 of the image also seems a bit weird, normally this starts with `iVBO`. I would suggest to reconvert it with a tool like: https://base64.guru/converter/encode/image
> 
> Let me know how it works!
> 
> Enjoy your day!

I added that then still had a bunch of tiny errors. Any clue whats happening? Clearly im a noob LOL

**Comment by Godspeed-exe** [comment]
Hi @ThaMacroMan 

I think the error is coming from the comma and the end, right before the closing } [here](https://github.com/cardano-foundation/cardano-token-registry/pull/3713/files#diff-4277cc979fd9a7f3dc2df545c0e696f46e3ed3df9b47edef6beeb36da92582b6R63)

You can also use tools like https://jsonlint.com/ to format / verify your JSON structure.

Let me know, we all learn!

**Comment by ThaMacroMan** [comment]
> Hi @ThaMacroMan
> 
> I think the error is coming from the comma and the end, right before the closing } [here](https://github.com/cardano-foundation/cardano-token-registry/pull/3713/files#diff-4277cc979fd9a7f3dc2df545c0e696f46e3ed3df9b47edef6beeb36da92582b6R63)
> 
> You can also use tools like https://jsonlint.com/ to format / verify your JSON structure.
> 
> Let me know, we all learn!

Fixed that, now getting this: 

[Error]   [Main.log#290] Failed to validate wallet metadata entry, error was: 'attestation verification failed for: description'.

Thanks so much for your help btw!!

**Comment by Godspeed-exe** [comment]
Hello @ThaMacroMan 

No worries, the world becomes a better place if we all help each other! 

The error message means that the signature of the Description field does not get verified. It seems like you changed the description and the signature is still the same. So I would update the signature again. 

If you look at [this line](https://github.com/cardano-foundation/cardano-token-registry/pull/3713/files#diff-4277cc979fd9a7f3dc2df545c0e696f46e3ed3df9b47edef6beeb36da92582b6L59) you can see:
- the value changed
- the signature is still the same

Does this make sense?

**Comment by Kartiiyer12** [comment]
Hi @ThaMacroMan 

Please go through the signing process again which will verify that you made those changes.
In your latest pull request validation we can see below errors, this indicates that those new values were not signed off correctly:

`Failed to validate wallet metadata entry, error was: 'attestation verification failed for: description'.`

**Comment by ThaMacroMan** [comment]
> Hi @ThaMacroMan
> 
> Please go through the signing process again which will verify that you made those changes. In your latest pull request validation we can see below errors, this indicates that those new values were not signed off correctly:
> 
> `Failed to validate wallet metadata entry, error was: 'attestation verification failed for: description'.`

Got it! Looks good now!!!

**Review by Godspeed-exe — APPROVED** [review]

**Comment by Godspeed-exe** [comment]
It does, congrats!

**Pull request merged**
