### PR TITLE
Added just the logo to the json file for BABYSHIB

### PR DESCRIPTION
**Pull request by LondonPass2024**
# Pull Request Template

## Description

Added the Logo to the original contents of the JSON for the BABY SHIB MOON PROJECT

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by LondonPass2024** [comment]
Require some help please. I am trying to add a LOGO to my original registration file. I created the logo using this tool as suggested by your colleague at the cardano foundation, but not sure if i've done something wrong in the code. 
Able to help please.

**Comment by Godspeed-exe** [comment]
Hello @LondonPass2024 

The user Adakondacoin is not working at Cardano Foundation, he's (or she) is a friendly contributor who decided to help out. 

With your submission there seem to be a few errors:
-  The Base64 value of the image should be without 'data:image/jpeg;base64,' - In my experience it always started with ivBOR, but when trying to re-encode your value I do get your logo, so I think this should be fine.
- You need to increment the sequenceNumber values, since  you are updating an existing registration, this is described in [this guide](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-update-my-entry-in-the-registry%3F). When you change a value you also need to re-sign all the values.
- you also need to add the signature for the logo - this is missing right now.
- the format of your JSON is not valid, it's missing a } at the end. You can verify / validate your JSON format through tools like [JSONLint](https://jsonlint.com/)

Good luck, let me know if you have any questions!

**Comment by LondonPass2024** [comment]
Thanks godspeed-exe, how do i create a signature?

**Comment by Godspeed-exe** [comment]
@LondonPass2024 you already generated a few signatures when you submitted the original file. The above linked guide describes how to generate those signatures using the token-metadata-creator

**Comment by LondonPass2024** [comment]
Thanks godspeed-exe. I used a GUI from https://cardano-native-token.com/ to generate the JSON. 
The Signature creation process for justs the Logo looks quite involved. Is there an easier way?

**Comment by Godspeed-exe** [comment]
@LondonPass2024 I don't think there is an easier way :sweat_smile: 
Maybe you can go through their process again and complete it with the existing keys? I'm not familiar with how that platform works.

**Comment by Godspeed-exe** [comment]
@adakondacoin is this your platform?

**Comment by LondonPass2024** [comment]
ok, i found out how to regenerate the json from teh website with the logo. I'll create a new pull request and close this one as i dont know how to amend it cleanly. Thanks for the help godspeed

**Pull request closed without merging**
