### PR TITLE
MemeBTC Governance Token Update: Image and Metada

### PR DESCRIPTION
**Pull request by MemeBTC21**
This commit transforms MemeBTC (Fingerprint: asset1lg2jcmcsa6x6jlsmkh34qd4k34v4y3dmddawz4, Policy ID: 7391b0502aa37ee7ef2428335a99b0425fb00cb6e7f3100a6886a4e5, Asset Name: 4d454d45425443) into our community's governance token! Key Updates:
Name: MemeBTC
Symbol: MEMEBTC
Total Supply: 2,100,000
New image signifies its governance role.
Description clarifies that holders have voting rights to shape the project's future.

# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by MemeBTC21** [comment]
Subject: MemeBTC Token Update, Governance Introduction, and Relaunch Assistance

Dear Support Team,

I'm seeking guidance on evolving the token structure for my project, MemeBTC.  After careful consideration, I've decided to:

Pivot Existing Tokens (2,100,000): Transform the existing MemeBTC tokens into dedicated governance tokens, granting holders exclusive voting rights on project decisions.
Relaunch with Corrected Supply (21 Million): Launch a new MemeBTC token with the intended 21 million supply as the project's primary token.
Key Requests for Assistance:

Governance Implementation: I'd appreciate best practices and recommendations for securely implementing the MemeBTC governance token model. Are there any specific tools or approaches recommended for Cardano-based governance tokens?
Relaunch Guidance (21 Million Token): What are the essential considerations for relaunching the core MemeBTC token with the corrected supply?
Community Announcement: I'd welcome feedback on my community announcement draft to ensure I clearly and effectively communicate these changes. (Draft attached)
Thank you for your expertise and support as I navigate this exciting evolution for MemeBTC!

Sincerely,

[@MemeBTC21](https://github.com/MemeBTC21)

https://memebtc.io/

**Comment by ScottBlaney** [comment]
If your minting policy is not locked you can still mint/burn tokens

**Comment by VladislavKudrin** [comment]
Hi @MemeBTC21,

not sure if this is the right place for the discussion, but:

1. If you want to implement a governance model with your minted token - you can look up these examples:
https://docs.geniusyield.co/gens-token/governances
https://lenfi.gitbook.io/docs/governance/governance-guide

Basically, a snapshot is taken before every proposal and users will get voting power according to their token holdings.

2. What is the decision behind turning MemeBTC into a governance token and creating another MemeBTC with updated supply? 
3. If submission is valid, please put it into mappings folder if not, close it.

Thanks!

**Comment by MemeBTC21** [comment]
Thanks, I'll check it out.

**Pull request closed without merging**
