### PR TITLE
Create d55bf9d2ad12cc55e4ed29d97c64dba0e4905d3c80f800449f3d51f0.json

### PR DESCRIPTION
**Pull request by Daawesomedrummer098**
# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [ ] Metadata related change
- [x] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by Godspeed-exe** [comment]
Hey @Daawesomedrummer098 

In this PR you are missing a comma after the value of the logo. It's maybe good to check the format of your JSON before you submit it because this seems to be a recurring issue.

There's also some other text in the JSON file which shouldn't belong there.

**Review by Daawesomedrummer098 — COMMENTED** [review]
Comma added, text deleted

**Comment by Godspeed-exe** [comment]
Hey @Daawesomedrummer098 

Your JSON seems to be missing a closing } at the end. You can best verify your JSON validity before submitting if you want to be sure.

**Review by Daawesomedrummer098 — COMMENTED** [review]
Added } at end

**Comment by Godspeed-exe** [comment]
Hey @Daawesomedrummer098 

There are still a few errors which is keeping this pull request from passing validation. Can you look at the descriptions here of what each field / value should be: https://github.com/cardano-foundation/cardano-token-registry#semantic-content-of-registry-entries

- Subject: should be concatenation of the policy id and hex of assetname: d55bf9d2ad12cc55e4ed29d97c64dba0e4905d3c80f800449f3d51f04368616e6765 -> this also impacts the filename of your json file > d55bf9d2ad12cc55e4ed29d97c64dba0e4905d3c80f800449f3d51f04368616e6765.json
- Policy: although this is option: The base16-encoded CBOR representation of the monetary policy script, used to verify ownership.

**Comment by Godspeed-exe** [comment]
Closed because of duplicate

**Pull request closed without merging**
