### PR TITLE
Add LindaLove and Stayk metadata | update SHUTA metadata

### PR DESCRIPTION
**Pull request by time2devnull**
# Pull Request Template

## Description

Add LindaLove metadata

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [x] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Review by crptmppt — CHANGES_REQUESTED** [review]
Your PR contains multiple mappings, I suggest you split it as individual PRs (one mapping per PR) so they can be individually processed. Apologies for the inconvenience.

**Comment by time2devnull** [comment]
Dear @crptmppt ,
Changes have been made now.

**Comment by time2devnull** [comment]
Dear @crptmppt ,

I was dumb enough to:
1. authenticate here through 3rd party tool which resulted in me committing twice using main github account and revealing my identity
2. deleting the fork right away out of panic instead of rebasing and wiping commits. 

Would you be so kind as to erase this PR from the repo history, please? I would prefer to remain anonymous due to significant pledge in my pool.

**Comment by crptmppt** [comment]
> Dear @crptmppt ,
> 
> I was dumb enough to:
> 
> 1. authenticate here through 3rd party tool which resulted in me committing twice using main github account and revealing my identity
> 2. deleting the fork right away out of panic instead of rebasing and wiping commits.
> 
> Would you be so kind as to erase this PR from the repo history, please? I would prefer to remain anonymous due to significant pledge in my pool.

I don't think this is feasible, however with the PR closed it should stay out of the repo
https://stackoverflow.com/questions/18318097/delete-a-closed-pull-request-from-github

**Comment by time2devnull** [comment]
Hi @crptmppt,

I have requested the removal from GitHub and they replied with "only repo admin can request that". They also suggest that admin could reply to them directly in that email, if I forward it. Do you think this is something that could be done? 

The reason here is that even though the PR is out of master, it's still searchable here /:

**Comment by crptmppt** [comment]
As noted earlier I do not believe this is feasible - thanks for forwarding relevant comms with github, no promises but trying to help.

**Comment by time2devnull** [comment]
> As noted earlier I do not believe this is feasible - thanks for forwarding relevant comms with github, no promises but trying to help.

Thanks, may I ask for your email address, please? or if you could send me a not at the email above?

**Pull request closed without merging**
