### PR TITLE
PEPE BULL RUN Token submission

### PR DESCRIPTION
**Pull request by Pepebullrun**
# Pull Request Template

## Description
Registration request for PEPE BULL RUN Token

### CODE REVIEW

**Comment by Kartiiyer12** [comment]
Hi @Pepebullrun Please add only one file under mappings folder and remove other two files. Only the file under mappings folder is considered for token registry.
Also, with 1,000,000,000 tokens and 5 decimal value the total token would be 10000.00000 (only 10 K) as the decimals will take 5 places. So please check the tokenomics to make sure you have right amount of tokens.

**Comment by Pepebullrun** [comment]
Thank you for your advice, the truth is that I uploaded the file several
times and each time it gave me an error during verification. I also did not
take into account the issue of decimals. I will review, delete the uploaded
files and upload it again correctly. Thank you for your time

**Comment by Pepebullrun** [comment]
Como hago para borrar todo los intentos de registro del token pepebullrun (PBull) y empezar de nuevo? Gracias

**Comment by Godspeed-exe** [comment]
@Pepebullrun 

In the latest pull request you are trying to delete the entire mappings folder. I think it's best that you start the process fresh on your side:
- delete your fork of the repo
- create a new fork of the repo
- upload your file into the mappings folder (don't touch any other files)
- create a new PR on this repo

This should work.

**Pull request closed without merging**
