### PR TITLE
Add a new token

### PR DESCRIPTION
**Pull request by odedNea**
# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by linconvidal** [comment]
Hey @odedNea! I’ve checked with the team, and we couldn’t reproduce the issue on our end. When we added the same base64 and signed it with our keys, the validation passed, so the logo seems fine. The attestation error might be related to a signature issue. Could you please review and update the signature?

**Comment by odedNea** [comment]
Hey @linconvidal 
Somehow the logo and the policy don't go together and the deployment fails.
I removed the policy field and now the deployment passes with the logo field.
If there's no logo field but the policy field exists, the deployment also passes.
Any idea what could be the issue?

**Comment by odedNea** [comment]
Hey @linconvidal 
Somehow the logo and the policy don't go together and the deployment fails.
I removed the policy field and now the deployment passes with the logo field.
If there's no logo field but the policy field exists, the deployment also passes.
Any idea what could be the issue?

**Comment by Godspeed-exe** [comment]
**Automated feedback**<br /><br />**Value:** <br />OTM<br /><br />**Attribute:** <br />ticker<br /><br />**Analysis:** <br />The acronym 'OTM' is generic and does not directly reference a well-known individual, brand, or entity in the Cardano ecosystem or the wider crypto ecosystem. Without additional context, it does not appear to be a violation.<br /><br />

**Comment by odedNea** [comment]
> Hey @odedNea! I’ve checked with the team, and we couldn’t reproduce the issue on our end. When we added the same base64 and signed it with our keys, the validation passed, so the logo seems fine. The attestation error might be related to a signature issue. Could you please review and update the signature?

I removed the logo in order to make sure that the metadata applies to my token, even without the logo for now

**Review by Kartiiyer12 — APPROVED** [review]

**Pull request merged**
