### PR TITLE
Ysara

### PR DESCRIPTION
**Pull request by nhantd292**
# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by nhantd292** [comment]
I got the following message: "Failed to validate wallet metadata entry, error was: 'attestation verification failed for: name' I edited the token name is there any standard for naming tokens

**Comment by Godspeed-exe** [comment]
**Automated feedback**<br /><br />**Value:** <br />YSARA<br /><br />**Attribute:** <br />name<br /><br />**Analysis:** <br />YSARA could potentially infringe on the brand YSARI, a known luxury yacht company. Even though the spelling differs slightly, such variations are often considered in identity and trademark protection. This could lead to confusion among consumers or stakeholders in relevant markets.<br /><br />**Value:** <br />BCH<br /><br />**Attribute:** <br />ticker<br /><br />**Analysis:** <br />BCH refers to Bitcoin Cash, which is a prominent cryptocurrency forked from Bitcoin. Using the abbreviation 'BCH' in itself is not a copyright infringement or impersonation, as it is commonly used across the crypto ecosystem to identify Bitcoin Cash.<br /><br />

**Comment by Godspeed-exe** [comment]
Hello @nhantd292 

The above automated feedback is handled through AI, an attempt to automate as much as possible. This is now pending manual verification, no need to take any action for now.

**Comment by Godspeed-exe** [comment]
Automatically closed because it's been more than 5 days since the last comment

**Comment by Kartiiyer12** [comment]
Hi @nhantd292 
The validation is failing for the name value in the JSON file. So if you can sign the data again and submit and the validation passes, we can approve and merge.

**Pull request closed without merging**
