### PR TITLE
ARF Token Registry Submission

### PR DESCRIPTION
**Pull request by arfsappyada**
# Pull Request Template

## Description

Registration request for the ARF Token on Cardano.
Please do the needful :)

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by arfsappyada** [comment]
Hello, 
The token logo is not visible since the update.
I think it is because the .json file also had a data sting for the image.

Please assist in the fix.
Thanks!

**Comment by cleanerm5** [comment]
Hi
On which platform is the image not visible?

arfsappyada ***@***.***> schrieb am Di., 9. Mai 2023, 22:43:

**Comment by arfsappyada** [comment]
Thank you for the prompt reply, I am checking on pool.pm & on Minswap.

**Comment by arfsappyada** [comment]
Seems to be working now!

**Comment by cleanerm5** [comment]
Really? So the sync usually can take up to 4 hours. Maybe it was delayed. Let me know if you need more support

**Comment by arfsappyada** [comment]
Yeah, I thought you may have fixed something.
I know it takes a bit of time but just got a li'l concerned.

Thanks for your support!

**Pull request merged**
