### PR TITLE
delete old BUKZ 

### PR DESCRIPTION
**Pull request by pehcastro**
changed name and description values to void for upload new .json file as update for #1391

### CODE REVIEW

**Comment by pehcastro** [comment]
@cleanerm5  this?

**Comment by cleanerm5** [comment]
@pehcastro Almost. You need to increment the sequenceNumber of the changed properties by one. That is why the validation fails at the moment. That is the procedure described [here](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-update-my-entry-in-the-registry%3F) at "Step 3".

**Comment by pehcastro** [comment]
@cleanerm5 for all sequenceNumber or only name and description?

**Comment by cleanerm5** [comment]
@pehcastro 

For the properties that were updated.

**Pull request closed without merging**
