### PR TITLE
Create ProjectSlimeResearch

### PR DESCRIPTION
**Pull request by LordPanda10**
Project: Slime Research, will add new policies with new slimes in the future.

# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [x] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by LordPanda10** [comment]
I'm not quite sure what else I'm needed to do from here on, I think as far as I understood from the guide, I just wait for a maintainer to review my project and then give the go-ahead once deemed that there's no other Project:  "SlimeResearch"

So hopefully all goes well and I did all I needed on my end 🤔

**Review by LordPanda10 — COMMENTED** [review]
We plan on working on two projects so I replaced original code (Single project) and added multiproject instead

**Review by crptmppt — CHANGES_REQUESTED** [review]
Your PR is failing automated checks - thank you for checking the "Checks" tab for more details, and correcting as required. If you're not sure of what is missing, consider looking into the repo README or the wiki for instructions, or mappings PRs that were recently merged.

(look at the wiki in this repo for submitting, AND Prs that were merged successfully - your format is off)

**Comment by LordPanda10** [comment]
I noticed you said my format is off... I'm not quite sure where to compare this towards other successful pull requests as I had troubles finding where others had their code at. But I just did what I could following Stales tutorial...  but hopefully taking off those two notes in the code helps fix it. Thank you for helping me out!!

**Comment by crptmppt** [comment]
Your PR is still failing the automated checks:
Look at the wiki entry on [how to prepare an entry](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-to-prepare-an-entry-for-the-registry-%28NA-policy-script%29) 
Then check out the entry on [how to submit it](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-to-submit-an-entry-to-the-registry)

Check out a [recently merged mapping](https://github.com/cardano-foundation/cardano-token-registry/pull/658/files) to see what the format should be like.

**Comment by LordPanda10** [comment]
Hey Frederic! Thank you for the links. I went over them and I honestly have no clue what have the stuff is in what you have.... like signatures and public keys.. I tried finding out how to find those but I couldn't find any videos and going to the cardano dev forums just has a 404 error...... anyways I changed the code back to single project and stuck with slimes and a single policy ID so I'm hoping this works but if it doesn't then I might have to close my PR... but we'll see how it goes. Here's the video I followed in case you might have been wondering where the confusion stems " https://www.youtube.com/watch?v=z6yPjed4sMI&t=57s " There isn't really much to go off of as someone with zero experience lol

Anyways hopefully the changes I made help, I guess I'll see what you think soon, thanks again Frederic!

**Review by LordPanda10 — COMMENTED** [review]
Changed multi project line to single project line

**Review by crptmppt — CHANGES_REQUESTED** [review]
it still is not in the right format - go through the links and the instructions provided.  (this is not mergeable as-is)

**Comment by crptmppt** [comment]
note: the video you linked was about trying to validate a project with CNFT.io (as third party)
This HERE is the Cardano Token Registry from the Cardano Foundation.
Both have different formats and instructions - see where you want to register your project!

**Comment by LordPanda10** [comment]
Dearest Frederic 

Lmao apparently I'm in the wrong place so I'm going to close my pull request. I'm sure there's probably still some merit to registering tokens here but I don't have enough background knowledge on where to find signing keys or signature keys as well as other stuff required for me to submit a merge request. Maybe I'll try again in the future after I learn more lol

Thank you for redirecting me, I'm going to close this request so thank you for helping me out

Sincerely,

BlindAssPandaBear lol

**Pull request closed without merging**
