### PR TITLE
Edit: Added website

### PR DESCRIPTION
**Pull request by StarsEyeView**
Added website url starseyeview.io to the metadata. Need to replace the old json file with this one.

# Pull Request Template

## Description

Added website url starseyeview.io to the metadata. Need to replace the old json file with this one.

## Type of change

- [ x] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by cleanerm5** [comment]
Hi @StarsEyeView 

the filename mappings/141de94d882e6426622898984d8861c4a69e0da5df8c930177926dd9534556 (1).json is wrong. please remove the " (1)" part from the filename.

**Comment by StarsEyeView** [comment]
I'd like edit to replace the first json file with a new one. I'm not sure
how to do this. I added a url to the updated file and would like to have it
in the metadata. Are there instructions on how to do that?

I thought I could just do a pull request for it. It won't allow me to
create a fork like I did when registering the token and editing the
metadata.

Any help would be appreciated.

Regards,
Luther Freeman

**Comment by StarsEyeView** [comment]
Hi,

I see now. I just need to edit the file name. I was confused for a moment.
Thanks for the review. I'll resubmit it later today.

Regards,

Luther Freeman

**Review by StarsEyeView — COMMENTED** [review]
Added a url to the metadata

**Comment by cleanerm5** [comment]
Hi @StarsEyeView 

Looks ok now but you still have the wrongly named file in the PR. I created a new PR (#2006) with only the correct file in it. Validation succeeded and I merged it.

Closing this one.

**Pull request closed without merging**
