### PR TITLE
Create Muggzie Coin

### PR DESCRIPTION
**Pull request by Muggzie76**
…475a.json

The Muggzie token for the New Mverse

# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by Muggzie76** [comment]
Beginning of the Mverse a beautiful all inclusive multi layer metaverse for any ones taste and style.

**Review by Muggzie76 — COMMENTED** [review]
Approved By Muggz

**Review by Everlucentvr — APPROVED** [review]

**Review by Everlucentvr — APPROVED** [review]
This is solid.

**Comment by Muggzie76** [comment]
Did I miss Something Here ? It's been 8 hours ,, Not sure if I did something wrong

**Review by cleanerm5 — APPROVED** [review]

**Pull request merged**
