### PR TITLE
HYDRA Token Submission

### PR DESCRIPTION
**Pull request by HydraCNFT**
# Pull Request Template

## Description

Registration request for HYDRA Token

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by cleanerm5** [comment]
Hi @HydraCNFT 
please remove the empty file from the PR. mappings/63383736346364353334383562323966366164393462663639663339396163373239303362346466316537306436613131396436353936654859445241.json

**Review by HydraCNFT — COMMENTED** [review]
Empty file removed from the PR.

**Comment by HydraCNFT** [comment]
Would you prefer that I redo a new request? @cleanerm5

**Comment by cleanerm5** [comment]
Hi @HydraCNFT 
As Hydra is a well known name in the Cardano space the vetting process takes a bit longer. I'll merge as soon as this is done. Sorry for the delay.

**Comment by HydraCNFT** [comment]
Hi @cleanerm5, we didn't think that would be an issue.

We've been building on Cardano for over a year under this name, we're [DOXXED by Bearmarket.io](https://bearmarket.io/doxxed/project-hydra/) (Ted Nation) and we've already accumulated three CNFT collections, all verified by JPG.Store ([Main](https://jpg.store/collection/hydraproject/)/[Event](https://www.jpg.store/collection/hydraeggs/)/[Promo](https://www.jpg.store/collection/hydraogpass/)).

All of our Policy IDs are locked and the $HYDRA token is already trading normally on [Minswap](https://app.minswap.org/pt-BR/swap?currencySymbolA=&tokenNameA=&currencySymbolB=c8764cd53485b29f6ad94bf69f399ac72903b4df1e70d6a119d6596e&tokenNameB=4859445241). Our community already has 280 holders and more than 3000 members on [Twitter](https://twitter.com/HydraCNFT) and [Discord](https://discord.gg/HydraProject/). We know that we don't have such expressive numbers but we have the whole project very well [documented](https://hydra-project.gitbook.io/litepaper/) and all of this can be verified in the links below:

DOXX: https://bearmarket.io/doxxed/project-hydra
Main Collection: https://jpg.store/collection/hydraproject
Event Collection: https://www.jpg.store/collection/hydraogpass
Promo Collection: https://www.jpg.store/collection/hydraeggs
Twitter: https://twitter.com/HydraCNFT
Discord: https://discord.gg/HydraProject
Whitepaper: http://docs.hydraproject.org
Website: http://hydraproject.org
[$HYDRA Token Pool on Minswap](https://app.minswap.org/pt-BR/swap?currencySymbolA=&tokenNameA=&currencySymbolB=c8764cd53485b29f6ad94bf69f399ac72903b4df1e70d6a119d6596e&tokenNameB=4859445241)

Unfortunately some of our members are trading fake tokens with the same name. Our effort is to prevent this from happening again. We were the gateway for many users who had never invested in crypto so we owe them some attention. I hope you understand and we are at your disposal if you want to meet the team.

**Comment by HydraCNFT** [comment]
Hello @cleanerm5, sorry for the insistence but today we had another case of a holder trading a fake token with our same name, how much longer do you think this merge could take? We depend on it for Minswap to verify our token.

Thank you for your attention.

image

**Comment by cleanerm5** [comment]
Hi @HydraCNFT 
I checked the background info provided and merged the PR. Sorry for the delay. However, it might be a good idea to amend the current description field to state that it is the "Hydra launchpad Ecosystem" instead of just the "Hydra Ecosystem" as it might be misleading for users.

**Comment by HydraCNFT** [comment]
Thanks @cleanerm5!
No problem, we will provide the changes, feel free to suggest any other changes you think are necessary.

**Pull request merged**
