### PR TITLE
Delete e58260a36677777f6a622beae74c8b00f831e9577e1aef65548fd7714a4152.json

### PR DESCRIPTION
**Pull request by JARStudios**
Submission for deletion of wrongly configured JAR token (e58260a36677777f6a622beae74c8b00f831e9577e1aef65548fd7714a4152.json).  
Metadata updated by following https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-delete-my-entry-from-the-registry%3F

# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [x] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by cleanerm5** [comment]
Hi @JARStudios 

the change looks almost good. Only issue is, that some of the signatures got duplicated (ticker, decimals, logo values) and need to be removed in order to let the validation succeed.

**Comment by JARStudios** [comment]
@cleanerm5 can we remove it manually from the file? We followed the guide each and every step. 
Looking forward to you reply :)

**Comment by cleanerm5** [comment]
@JARStudios Yes sure. In the end it is just a json file. Just remove the duplicate ones from the properties that weren't changed.

**Comment by JARStudios** [comment]
@cleanerm5 I will close this pull request for now and will submit a new one with the corrected metadata file.

**Pull request closed without merging**
