### PR TITLE
Update da2f0678f09b807e93048e9157cd94be794c995ba1c1ef5a0ca8b31c.json

### PR DESCRIPTION
**Pull request by 7robbie5**
# Pull Request Template

## Description

Modified metadata and the URL of the project

## Type of change

- [ X] Metadata related change
- [ ] Other

## Checklist:

- [ X] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

I made a new one from scratch. mappings/9a3c722722dda2f407d639c5cda46845c9090f204b61677765d1279348616c616c2042726f6b6572.json 

Do I still have to change the sequence number, because its a new one.

### CODE REVIEW

**Comment by cleanerm5** [comment]
Hey @7robbie5 

When trying to update metadata you must follow along the instructions provided in our Wiki. In your case you need to also increment the sequenceNumber by 1 and sign the new metadata json file.

https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-update-my-entry-in-the-registry%3F

**Comment by 7robbie5** [comment]
I already saw it in the error logs. Will do that.

**Comment by 7robbie5** [comment]
I made a new one from scratch. Does this mean I still need to increment the value.

**Comment by cleanerm5** [comment]
Hey @7robbie5 

please remove the "deletion" from the PR. Deletions are not allowed directly. For deletions you must follow along the instructions provided in the [Wiki](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-delete-my-entry-from-the-registry%3F)

**Comment by 7robbie5** [comment]
I added the the file to delete the old entry and you also have my new entry. I added the file signed with higher sequence number etc. Let me know if this is enough for deletion. And you already have the new file. Sorry for the mess i am creating, long time ago since last time.

**Comment by cleanerm5** [comment]
Changes are merged with #1942

There was only a minor issue in the end with the changes to the file that should be deleted (signatures were duplicated which was detected as a change and as the sequence number was not incremented it was reported as a validation error).

File to add is now added and file to delete has been deleted after #1942 validation succeeded.

**Comment by 7robbie5** [comment]
I know I'm a pain but I'll make a mess of it otherwise. I uploaded another new version and an old one to delete the previous one. It gave one error because it also sees the old one, the original file.

**Comment by 7robbie5** [comment]
https://tokens.cardano.org/metadata/9a3c722722dda2f407d639c5cda46845c9090f204b61677765d1279348616c616c42726f6b6572 still not visible. I deleted the original one. But they send me an incorrect one. So i did a new deletion file and added the last version which should be visible at https://tokens.cardano.org/metadata/9a3c722722dda2f407d639c5cda46845c9090f204b61677765d1279348616c616c42726f6b6572

**Pull request closed without merging**
