### PR TITLE
Create e5046e2991f35552fdde193290bb5c3586d70f4166f867ab06243d82534845524f token

### PR DESCRIPTION
**Pull request by SuperHeroToken**
# Pull Request Template

## Description

We want to register Super Hero token an added all metadata here.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by SuperHeroToken** [comment]
@cleanerm5

**Comment by SuperHeroToken** [comment]
@AdirkAda

**Comment by SuperHeroToken** [comment]
@Kartiiyer12

**Review by Godspeed-exe — APPROVED** [review]
Approved

**Pull request merged**
