### PR TITLE
Update bb1afa523a767b7ae5c5a6083af24eb68a91fe7e583680c822d28ba1494e4b…

### PR DESCRIPTION
**Pull request by WhitemanE0**
….json

decimals 3

# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by WhitemanE0** [comment]
What's up now? the only change:

--                "signature": "b235610f6b52c5c7f58f79f76cba377f6491ed72eb623ef76acbcb2a654b757477810d30d6e10a79e898d1b42009bc83991475ddd79ae85e311abc349afd8001"
++                "signature": "45d5bf4c2ba8b143711eb7cd85209352bd5de00a726dfae170e07c35880ae260301d19be0d47d75cdbe557b72b9cec2870a540ef8223e73ba0736601828b160d"

--       "sequenceNumber": 0,
--        "value": 2
++        "sequenceNumber": 1,
++       "value": 3

No curley brackets change

**Comment by cleanerm5** [comment]
The signature for decimals is invalid. Did you change the sequenceNumber before or after the signing? If you did it after the signing that's the issue.

**Comment by cleanerm5** [comment]
@WhitemanE0 can I consider this PR as obsolete as you did the changes with another PR?

**Comment by cleanerm5** [comment]
Closed. No response within the last 15 days.

**Pull request closed without merging**
