### PR TITLE
d55bf9d2ad12cc55e4ed29d97c64dba0e4905d3c80f800449f3d51f0436861…

### PR DESCRIPTION
**Pull request by Daawesomedrummer098**
…6e6765

# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by Kartiiyer12** [comment]
Hi @Daawesomedrummer098,

There is an error with the submission. The file was submitted without the .json extension.

Please fix this and correct the submission so that it can be merged.

**Comment by Godspeed-exe** [comment]
Hello @Daawesomedrummer098 

Also, your "subject" value consists of below, which is not correct.

d55bf9d2ad12cc55e4ed29d97c64dba0e4905d3c80f800449f3d51f0 = correct policy id
asset1x2mt2dvhm7z4lp073qx3hyee8xfdag60z9jjeg = is incorrect. This is should be 4368616e6765, which is the Hex format of "Change".

so your "subject" value should be "d55bf9d2ad12cc55e4ed29d97c64dba0e4905d3c80f800449f3d51f04368616e6765".

Be sure to resign this value after you changed it..

**Review by Daawesomedrummer098 — COMMENTED** [review]
Updated Subject and added .json to end of file name

**Comment by Godspeed-exe** [comment]
@Daawesomedrummer098 

There is still something weird going on with your submission.. The only thing that I can spot is the "policy" value which holds the policyId. The description of this field is `The base16-encoded CBOR representation of the monetary policy script, used to verify ownership. `

So this is based off of your policy.script file.
The below link also describes the steps on how to do this. https://input-output-hk.github.io/offchain-metadata-tools/

Hope that helps!

**Comment by Godspeed-exe** [comment]
@Daawesomedrummer098 maybe this guide is clearer / more concise compared to the previous one: https://github.com/cardano-foundation/cardano-token-registry/wiki/How-to-prepare-an-entry-for-the-registry-%28NA-policy-script%29#step-3-add-required-fields

**Comment by Daawesomedrummer098** [comment]
i see that in a verified token in the mappings folder their "publickey" is
the same for each field. I have my public sign key and can update and can
change that, But the "signature" is different for each field. How Do i find
that string of letters and numbers for the "signature" of each field?

**Comment by Godspeed-exe** [comment]
Hello @Daawesomedrummer098 

Since I haven't heard back I'm closing this pull request, but feel free to make the above change and pull again.

Happy holidays!

**Comment by Daawesomedrummer098** [comment]
the tools linked above dont work, there is 2 links for the off chain metadata tools. Both comeback with a error 404

**Comment by Daawesomedrummer098** [comment]
You said " The signature is generated by taking the value (for example, TICKER) and digitally signing it with your policy.skey. That's why it's different for each attribute and also why it changes every time you change even 1 character in a specific value.

The tools listed above should handle this entire process for you. "        How do I digitally sign it with my Policy.skey?

**Comment by VladislavKudrin** [comment]
There is a full tutorial at https://input-output-hk.github.io/offchain-metadata-tools/#build-the-project-from-source on how to install nix project (token-metadata-creator) and use it to sign your metadata.

There is also an option to install binaries from https://github.com/input-output-hk/offchain-metadata-tools/releases/download/v0.4.0.0/token-metadata-creator.tar.gz
and use them directly without nix installation procedure

Feel free to check it out!

**Pull request closed without merging**
