### PR TITLE
Create Banana Token for CardanoApes 127fb4d51dc05d6b8a58aba62c1e0d9a3f6a702026a22059f434e632.json

### PR DESCRIPTION
**Pull request by cardanoapes2022**
# Pull Request Template

## Description

Utility Token for CardanoApes and CardanoApesMetaverse

https://cardanoapes.club/
https://twitter.com/ApesCardano

## Type of change

- [x] Metadata related change
- [x] Other

## Checklist:

- [x] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by cleanerm5** [comment]
Hi @cardanoapes2022 

looks like you signed the file twice. Could you please one of the signature objects for each property so that there is only one left?

**Comment by cardanoapes2022** [comment]
Changed and removed double signature. Thanks for checking again

**Comment by cardanoapes2022** [comment]
Updated the file - should work now - Thanks!

**Review by cleanerm5 — CHANGES_REQUESTED** [review]
Please move the file to the "mappings" subfolder

**Comment by cardanoapes2022** [comment]
Sorry - now!

**Review by cleanerm5 — APPROVED** [review]

**Comment by cardanoapes2022** [comment]
@cleanerm5 Is there something wroing with the data because cardanoscan is saying that the token is not veryfied:

https://cardanoscan.io/token/127fb4d51dc05d6b8a58aba62c1e0d9a3f6a702026a22059f434e63242616e616e61

Tahnks for your help

**Pull request merged**
