### PR TITLE
TheBHub token submission

### PR DESCRIPTION
**Pull request by TheBHubIO**
# Pull Request Template

## Description

Registration request for TheBHub token (updates) :)

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by cleanerm5** [comment]
Hey @TheBHubIO 

could you please increment the sequenceNumber of each property where you whether changed the value or added/changed signatures and do the signing again? Same thing you did for the decimals property.

**Comment by cleanerm5** [comment]
Hey @TheBHubIO 

could you please increment the sequenceNumber of each property where you whether changed the value or added/changed signatures and do the signing again? Same thing you did for the decimals property.

**Comment by TheBHubIO** [comment]
> Hey @TheBHubIO
> 
> could you please increment the sequenceNumber of each property where you whether changed the value or added/changed signatures and do the signing again. Same thing you did for the decimals property.

Hello @cleanerm5 
Sure, I just wanted to update the decimals; but I didn't sign the draft in the same key order (first commit), so I readjust it for the last commit. Everything should be ok now, please let me know if not.

Thanks :)

**Comment by cleanerm5** [comment]
Hey @TheBHubIO 

seems as if the signatures are wrong (at least thats what the validation complains about). Did you sign it after changing the sequenceNumber or before? The sequenceNumber is included in the signature that's why you must sign the file after incrementing the sequenceNumber.

**Comment by TheBHubIO** [comment]
> Hey @TheBHubIO
> 
> seems as if the signatures are wrong (at least thats what the validation complains about). Did you sign it after changing the sequenceNumber or before? The sequenceNumber is included in the signature that's why you must sign the file after incrementing the sequenceNumber.

I might have changed it afterward... I corrected it, if should be ok now.
Thank you for the support.

**Review by cleanerm5 — APPROVED** [review]

**Pull request merged**
