### PR TITLE
Modify SHUTA description to fit Daedalus tooltip

### PR DESCRIPTION
**Pull request by time2devnull**
# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [x] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by time2devnull** [comment]
Hey @crptmppt , 
Just highlighting this re-opened PR so that it doesn't drown amongst others

**Review by crptmppt — APPROVED** [review]

**Comment by time2devnull** [comment]
I am very sorry to interrupt you again @crptmppt , but I think that this PR could be merged already? I have opened a [suggestion](https://github.com/cardano-foundation/cardano-token-registry/issues/125) of how can this kind of situations get better visibility

**Comment by crptmppt** [comment]
@time2devnull  something weird is going on,looking at the Check it seems to b deleting a mapping - on hold for now (it appears to try deleting ec5d618931d59ca06da2ce203366177cf75650f890062ff07976a52d6e6577546f6b656e.json ... which should trigger a CI fail?)

**Review by crptmppt — CHANGES_REQUESTED** [review]
suggest you setup a separate PR - currently on hold until sorted out

**Pull request closed without merging**
