### PR TITLE
Revert "WingRiders"

### PR DESCRIPTION
**Pull request by szist**
Reverts cardano-foundation/cardano-token-registry#2243

Reverts the fake WRT token registration. The real WRT asset metadata is here https://www.wingriders.com/wrt
on cardano `asset18v68f0vgv2nc3at8cuuem7f3fztwqcq2usgjyp`

### CODE REVIEW

**Comment by szist** [comment]
I see the tests are failing @cleanerm5 . What is the recommended path here? Changing the metadata to reflect these are fake tokens?

**Comment by cleanerm5** [comment]
Hi @szist 

You need to follow these instructions for deleting metadata: https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-delete-my-entry-from-the-registry%3F

This is the same procedure as for updating token metadata but with specified values for the name and description fields.

We will then do the deletion if the validation of those changes did work.

**Comment by szist** [comment]
This policy keys are held by the fake token's creator. The original WRT tokens (I linked for their website) were not minted with a legacy minting policy requiring signatures, but using a plutus fixed supply policy script (seen here: https://github.com/wingriders/minter and https://cardanoscan.io/transaction/0516d8ea93efa37fc79dd0ae07d37922f077d3bbee55a95b2e9fb41b53b18d9a?tab=tokenmint )

The correct WRT token PR was added here: https://github.com/cardano-foundation/cardano-token-registry/pull/1859

**Comment by cleanerm5** [comment]
Hi @szist 

thanks for clarifying. I will the metadata set referred to by this PR because it has been registered against our [Terms of Use](https://github.com/cardano-foundation/cardano-token-registry/blob/master/Registry_Terms_of_Use.md) according to section "Publishing Information via the Cardano Registry" and the infringement of other parties IP.

**Review by cleanerm5 — APPROVED** [review]
This will be deleted because it is an IP infringement (trying to impersonate another company).

**Pull request merged**
