### PR TITLE
POWER Token Submission

### PR DESCRIPTION
**Pull request by nftprojectshop**
# Pull Request Template

## Description

Registration request for POWER token, thanks!

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [x] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by nftprojectshop** [comment]
validation failed for some reason, can you please let me know if I need to do anything else. thanks.

**Comment by VladislavKudrin** [comment]
> validation failed for some reason, can you please let me know if I need to do anything else. thanks.

Hi @nftprojectshop,

it is failing because you have additional file in the root folder; Please remove the 6c8e562f861061c6ccd24ba11560473e5e375f6bf111fb93efa6c3534845524f.json file and only leave the one in the mappings folder:
mappings/6c8e562f861061c6ccd24ba11560473e5e375f6bf111fb93efa6c3534845524f.json

Thanks!

**Comment by nftprojectshop** [comment]
> > validation failed for some reason, can you please let me know if I need to do anything else. thanks.
> 
> Hi @nftprojectshop,
> 
> it is failing because you have additional file in the root folder; Please remove the 6c8e562f861061c6ccd24ba11560473e5e375f6bf111fb93efa6c3534845524f.json file and only leave the one in the mappings folder: mappings/6c8e562f861061c6ccd24ba11560473e5e375f6bf111fb93efa6c3534845524f.json
> 
> Thanks!

Hi there, ok thanks. I removed that and updated the file in mappings. Hope that is ok now, thanks very much. Appreciated.

**Comment by VladislavKudrin** [comment]
@nftprojectshop,

now it seems like your signature for the name is not valid: Failed to validate wallet metadata entry, error was: 'attestation verification failed for: name'.

I guess it would fail for other fields too, if it had the chance to verify them. Please resign the file and update the PR.

You can verify your file before you submission with: token-metadata-creator validate {subject}.json

**Comment by VladislavKudrin** [comment]
Closed due to inactivity

**Pull request closed without merging**
