### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ClashAlex**
# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by Godspeed-exe** [comment]
**Automated feedback**<br /><br />**Value:** <br />We love to hate Cardano Warrior so much that we created $FUKCARDANOWARRIOR!!! - $GLDSNEK Team Haters Club Coin 1/5… Utility = Hate !!!<br /><br />**Attribute:** <br />description<br /><br />**Analysis:** <br />The value appears to be targeting 'Cardano Warrior,' which could be considered a well-known entity or individual within the Cardano ecosystem. This name-calling and creation of a coin based on hate can be seen as impersonation or defamation, especially since it uses variations of the targeted name in a negative manner. Additionally, the mention of '$GLDSNEK' could be related to another entity in the crypto ecosystem, adding another layer of potential infringement.<br /><br />**Value:** <br />please check files manually<br /><br />**Attribute:** <br />logo<br /><br />**Analysis:** <br />The image contains the text 'CARDANOWARRIOR DOXXED' and depicts an individual, which suggests it might be impersonating or revealing someone's identity in the Cardano ecosystem.<br /><br />

**Comment by ClashAlex** [comment]
Ok….

This is all good natured, and with the consent and blessing of cardano warrior.

Would it help if I get him to make a statement or something? Or can the token just not be registered?


Sent from my iPhone

On 18 Jul 2024, at 20:29, Michiel B ***@***.***> wrote:

﻿

Automated feedback

Value:
We love to hate Cardano Warrior so much that we created $FUKCARDANOWARRIOR!!! - $GLDSNEK Team Haters Club Coin 1/5… Utility = Hate !!!

Attribute:
description

Analysis:
The value appears to be targeting 'Cardano Warrior,' which could be considered a well-known entity or individual within the Cardano ecosystem. This name-calling and creation of a coin based on hate can be seen as impersonation or defamation, especially since it uses variations of the targeted name in a negative manner. Additionally, the mention of '$GLDSNEK' could be related to another entity in the crypto ecosystem, adding another layer of potential infringement.

Value:
please check files manually

Attribute:
logo

Analysis:
The image contains the text 'CARDANOWARRIOR DOXXED' and depicts an individual, which suggests it might be impersonating or revealing someone's identity in the Cardano ecosystem.

**Comment by Godspeed-exe** [comment]
Hey @ClashAlex 

The above is fully automated feedback. Who is Cardano Warrior? 🙈 
How can we reach out to him to verify that he approves of this?

**Comment by ClashAlex** [comment]
He is a member of the $gldsnek discord team, would you like an email address for him, or to reach out to him on discord?
________________________________

**Comment by Kartiiyer12** [comment]
Email would be good.

**Comment by ClashAlex** [comment]
Cardano Warrior has said that he does not want to give his email address out, but he posted this message in the GLDSNEK server:

[Image]

I hope that is adequate for you to understand that this is a fun token being released with his knowledge. There was a contest on the discord server to choose the image for the token and the community voted, all with his full knowledge. I understand if you need to confirm this, so here is a discord invite for the server : https://discord.gg/YdyCyCEB6K

Please let me know if you need any more information, thank you for helping look into this
[https://cdn.discordapp.com/splashes/1210651319396733018/6f80836ec207ec4de1efcfb6a32a9c82.jpg?size=512]<https://discord.gg/YdyCyCEB6K>
Join the Golden Snakes - $GLDSNEK Discord Server!<https://discord.gg/YdyCyCEB6K>
Check out the Golden Snakes - $GLDSNEK community on Discord – hang out with 947 other members and enjoy free voice and text chat.
discord.gg

________________________________

**Review by VladislavKudrin — APPROVED** [review]

**Pull request merged**
