### PR TITLE
Update Meemcoin's token logo

### PR DESCRIPTION
**Pull request by Meemcoin**
# Pull Request Template

## Description

Would like to update the token logo
token logo
.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by Godspeed-exe** [comment]
**Automated feedback**<br /><br />**Value:** <br />Another high quality meemcoin on Cardano<br /><br />**Attribute:** <br />description<br /><br />**Analysis:** <br />The phrase 'Another high quality meemcoin on Cardano' does not appear to impersonate a well-known individual or brand. It is a general statement referring to a meme coin on the Cardano blockchain, without invoking any specific names or trademarks.<br /><br />

**Comment by Meemcoin** [comment]
I am having the hardest time trying to get this logo updated, can someone please respond in here?

**Comment by Godspeed-exe** [comment]
Hello @Meemcoin 

When I look at the Validate-Metadata flow I can see below error message. When you are updating an existing you have to increment the sequenceNumber and make sure to re-sign the values. Please have a look at this Wiki that explains it step by step: https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-update-my-entry-in-the-registry%3F

`but the new sequence number '0' is not greater than the old sequence number '0'.`

I also see that your logo is a URL, this should be a base64 string. So you can convert your image into base64 strings with tools like https://base64.guru/converter/encode/image

Let us know if that works!

**Comment by Meemcoin** [comment]
Thank you for getting back to me! I will look into this further!

**Pull request closed without merging**
