### PR TITLE
Tschannen, DSwiss and SeSa Token

### PR DESCRIPTION
**Pull request by tschannen**
# Pull Request Template

## Description

Adds 3 tokens to registry: Tschannen token, DSwiss token, SeSa token. Combined them for simplicity reasons, please let me know if you require 3 independent PRs.

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [x] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by tschannen** [comment]
anything missing to process this PR?

**Comment by tschannen** [comment]
@admin-cf  Can you please provide an update / what blocks merging this PR? Thank you very much!

**Review by admin-cf — CHANGES_REQUESTED** [review]
Hi tschannen,

We are not supporting batch submissions at present. Could you please break up your submission into 3 separate PR's, one for each record. thanks you.

**Comment by tschannen** [comment]
Alright, thank you @admin-cf ! Just opened 3 independent PR instead, will with that close this one.

**Pull request closed without merging**
