### PR TITLE
Create Deadly Token Submission

### PR DESCRIPTION
**Pull request by Deadlyhallos**
This for DeadlyHallos

# Pull Request Template

## Description

Registrations request For Deadly Token :)

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by Deadlyhallos** [comment]
any wrone

**Comment by Godspeed-exe** [comment]
If you check the Details of the automated process with the "red X": https://github.com/cardano-foundation/cardano-token-registry/actions/runs/7723032666/job/21052303967?pr=3980 

This shows below. Basically this says "your filename does not match the policy&asset". It's just named "Deadly" which is incorrect. This needs to changed as mentioned in the other pull requests.

image

**Comment by Deadlyhallos** [comment]
Does that mean this is ok now?

**Comment by Godspeed-exe** [comment]
Not okay. Closed because of duplicates

**Pull request closed without merging**
