### PR TITLE
Create ea153b5d4864af15a1079a94a0e2486d6376fa28aafad272d15b243a534841…

### PR DESCRIPTION
**Pull request by realdecimalist**
…524453.json

# Pull Request Template

## Description

Created ea153b5d4864af15a1079a94a0e2486d6376fa28aafad272d15b243a534841524453.json for Cardano Token Registry submission.

## Type of change

- [ ] Metadata related change
- [X] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Review by realdecimalist — COMMENTED** [review]
Updated hash script for policy id. Not sure if I am using the right syntax. Instructions and merged commits from others seem contradictory.

**Comment by realdecimalist** [comment]
If unsuccessful--seeking feedback/guidance on syntax.

**Comment by realdecimalist** [comment]
@cleanerm5 I am having lots of trouble completing this process as this is a CIP-68 token. I have attached a screenshot with what I believe is the monetary policy script.

Also, here is the link to the Mint Tx: https://cardanoscan.io/transaction/fc68097ee3978b3aa9bfa338615be8d662874e2e7da08fb35ded5d74066f1950?tab=referenceinputs

Please let me know what else is needed. Thank you!


image

**Comment by realdecimalist** [comment]
@cleanerm5 

Type
PLUTUS_V2

Hash
ea153b5d4864af15a1079a94a0e2486d6376fa28aafad272d15b243a

Script
5909910100003333232323232323232323232322222232533300b3232323232533301000114a22a6602292010e726573756c74203f2046616c73650014a064a66602066e1d20000011323232323232323232533301900114a22a66034921136d696e745f726573756c74203f2046616c73650014a0646464646464646464a66604266e1d2000009132323232325333026533302600114a22a6604e92011769735f6d696e745f73756363657373203f2046616c73650014a02a66604c006294454cc09d24011c69735f636f72726563745f706f6c6963795f6964203f2046616c73650014a02940ccccc8c8c8c88888c8c8c94ccc0c14ccc0c14ccc0c000c5288a99818a4811a74785f7369676e65645f62795f6f776e6572203f2046616c73650014a02a666060004294454cc0c524011b69735f6265666f72655f6c6f636b5f74696d65203f2046616c73650014a0294054ccc0c00045288a99818a491a69735f616d6f756e745f706f736974697665203f2046616c73650014a02940cdc42400000664a66605e66e1d2000001132323322323253330353370e90010008991919b88001005375a607800260660042940c0cc004cc0bcc0c4cc0bcc0c4009200248000cc0b4c0bc021200e001375a606c002605a0082944c0b400cc8c94ccc0bccdc3a400000226464660166eb0cc0b4c0bc0212010001375c606c002605a00426464660126eb0cc0b4c0bc02120002323253330343370e90000008992503032002132323371e00c0026eb8c0ec004c0c8008c0c8004cc0b8c0c0cc0b8c0c0cc0b8c0c00052002480012000375c606c002605a004605a0026605260560069000180080091129998170010a5013232533302c300300214a2266600a00a002006606400660600046002002444a66605800429404c8c94ccc0a8cdc78010018a5113330050050010033030003375c605c00403203e03c0026466600a0020286eb8cc084c08c00d2002300900d3371e6eb8cc07cc08400520000123028001301f017153330213370e900100489919191919192999813a999813a9998138010a51153302849011769735f6275726e5f73756363657373203f2046616c73650014a02a66604e002294454cc0a124011969735f6275726e5f666565735f70616964203f2046616c73650014a0294054ccc09c0105288a998142491c69735f636f72726563745f706f6c6963795f6964203f2046616c73650014a02940cccccc8c888888c8c8c8c8c8c8c8c94ccc0d54ccc0d54ccc0d400c5288a9981b24811e69735f6665655f706169645f746f5f61646472657373203f2046616c73650014a02a66606a004294454cc0d924011a69735f616d6f756e745f6e65676174697665203f2046616c73650014a0294054ccc0d40045288a9981b2491769735f6665655f706f736974697665203f2046616c73650014a02940cdc42400000866e2001d20003371200400266602264a66606c0022a6606692010c61696b656e3a3a6572726f720016132533303700113237566606060640029001181c8010a9981a24810c61696b656e3a3a6572726f72001630390013300a37586605a605e01290021299981919baf3302e3030001480000244cdd7998171818000a400866e952004330370054bd700a500070063370666e0800800520d00f3370690504e00a41a01e66e0520000023374a9000198191ba900333032375200497ae03001001222533302d00214bd70099192999815980180109981800119980280280080189998028028008019818801981780100d01080a9bae33022302400448008008c94ccc0980045288a99813a491a69735f616d6f756e745f6e65676174697665203f2046616c73650014a066e20005200032333005001014375c6604260460069001180480699b8f375c6603e604200290000091814000980f80b8a5022232323253330263370e90010008a40002646eb4c0b4004c090008c090004c94ccc094cdc3a4004002298103d87a8000132323300800100537566058002604600460460026600c0060046002002444a66604a004298103d87a800013232323253330253371e00a002266e9520003302a375000497ae01333007007003005375c604c0066eb4c098008c0a400cc09c008c0040048894ccc08c008530103d87a800013232323253330233371e00a002266e95200033028374c00497ae01333007007003005375c60480066eacc090008c09c00cc0940088cc008005221003001001222533302000214bd6f7b630099191919299981019b8f0050011003133025337606ea4004dd30011998038038018029bae30210033756604200460480066044004602e01c6eacc074004c074004c070004c06c004c068004c040018dd7180b80098070010a50300e0013014001301400230120013009002149858c800ccc88c94ccc034cdc3a400000226464a666026602c0042649318028008a998082481334c6973742f5475706c652f436f6e73747220636f6e7461696e73206d6f7265206974656d73207468616e20657870656374656400163014001300b0021533300d3370e9001000899192999809980b00109924c600a0022a66020921334c6973742f5475706c652f436f6e73747220636f6e7461696e73206d6f7265206974656d73207468616e20657870656374656400163014001300b0021533300d3370e90020008a99980898058010a4c2a6601c92011d4578706563746564206e6f206669656c647320666f7220436f6e7374720016153300e4912b436f6e73747220696e64657820646964206e6f74206d6174636820616e7920747970652076617269616e740016300b001232533300c3370e9000000899191919299980a180b8010a4c2a66022921334c6973742f5475706c652f436f6e73747220636f6e7461696e73206d6f7265206974656d73207468616e2065787065637465640016375c602a002602a0046eb8c04c004c02800854cc0352412b436f6e73747220696e64657820646964206e6f74206d6174636820616e7920747970652076617269616e740016300a00100233001001480008888cccc01ccdc38008018069199980280299b8000448008c03c0040080088c018dd5000918021baa0015734ae7155ceaab9e5573eae815d0aba24c0150d8799fd8799f581cdfcb5f6c42f7529f31be82e0e68a75c2db94e425409770341011ef80ffd8799fd8799fd8799f581c5ea481523030b23a495286ca1a18bd141a493e9b5a19d889953f6cdbffffffff004c0150d8799fd8799f581cc01af7680f1d86376796153cb9ba0eb16194ad7d6f292c2b73ee5892ffd8799fd8799fd8799f581ccd7f36c931d1b261c4714473794abf5143cd2c04705730622a304c2effffffff004c010dd8799f1b0000018d9414ab18ff0001

**Comment by realdecimalist** [comment]
@cleanerm5 All checks passed. Yay!!

**Review by cleanerm5 — APPROVED** [review]

**Pull request merged**
