### PR TITLE
Added the ADAO token v2, which shall be distributed soon.

### PR DESCRIPTION
**Pull request by Riley-Kilgore**
# Pull Request Template

## Description

Added the ADAO Governance Token version 2

## Type of change

- Added metadata for the token

## Checklist:

- [x] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by cleanerm5** [comment]
Hi @Riley-Kilgore 

the mappings json file looks like you did not sign and finalize it because there are no signatures included. Could you please do that according to Steps 5 and 6 described [here](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-to-prepare-an-entry-for-the-registry-%28NA-policy-script%29) and reissue the PR?

**Comment by Riley-Kilgore** [comment]
Yo, this is a plutus script policy.
There is not a signature to apply, similar to https://github.com/cardano-foundation/cardano-token-registry/commit/66a2981d37b7da9ee1d06067013aa9952d01fad1

Thanks!

**Comment by Riley-Kilgore** [comment]
@cleanerm5 - Just tagging you for reference.

**Comment by Riley-Kilgore** [comment]
@adam-cf Tagging you as well since you approved the previous PR from ADAO.

**Pull request closed without merging**
