### PR TITLE
put your hands up token

### PR DESCRIPTION
**Pull request by cardano-tools-nft**
# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by KornerzZZ** [comment]
I'm not good at github, does this keep the policy intact?

**Comment by wutzebaer** [comment]
> 
> 
> I'm not good at github, does this keep the policy intact?

No it registers your token in the cardano token registry, which is used by daedalus etc. to find metadata about it

**Comment by KornerzZZ** [comment]
So what do I need to do for a fixed policy TT 

However, I thank you for the reply.

**Comment by wutzebaer** [comment]
> 
> 
> So what do I need to do for a fixed policy TT
> 
> However, I thank you for the reply.

Hi just join our telegram channel https://t.me/joinchat/XrlIF21NDzAyODUy then we can try to answer your questions

**Review by crptmppt — APPROVED** [review]
not that it appears you've created two tokens that use the same policyID, but diff names, and are now registering similar metadata. If this isn't what is intended suggest you push a PR to remove the wrong one.

**Comment by KornerzZZ** [comment]
it was my mistake I don't know how it works. How to press PR please guide me I'm a newbie

**Comment by crptmppt** [comment]
For Github guides you can search online - for the policy, not sure what you mean by "does this keep the policy intact". Thisis just dealing with metadata - for other concerns you might have to go on the dev channels.

**Comment by KornerzZZ** [comment]
ok thanks for the advice I will be careful using🙏

**Pull request merged**
