### PR TITLE
Honey

### PR DESCRIPTION
**Pull request by ClashAlex**
# Pull Request Template

## Description

Please add Honey token

## Type of change

Add new token

### CODE REVIEW

**Review by Godspeed-exe — APPROVED** [review]

**Comment by ClashAlex** [comment]
Thank you.

The logo does not seem to display, for example on minswap - did we do something wrong with the metadata or is this something that may take more time to be reflected?

Thank you for your help
Sent from my iPhone

On 4 Jan 2024, at 10:10, Michiel B ***@***.***> wrote:

﻿

Merged #3815<https://github.com/cardano-foundation/cardano-token-registry/pull/3815> into master.

**Comment by Godspeed-exe** [comment]
Hello @ClashAlex 

On CardanoScan it looks good: 
image

The HONEY token on MinSwap seems to be a different policyId though? 
Are you sure you used the correct policyId and private keys to generate this submission?
image

**Comment by ClashAlex** [comment]
Hi,

This is the one I mean, it has the same policy ID beginning 3abb but the image remains a question mark

thank you for replying

Alex
________________________________

**Comment by Godspeed-exe** [comment]
Hi @ClashAlex 

Where are you looking, because I don't see a LP on MinSwap for any token of PolicyID `3abb90e183fe502243b4ae02d36f47548073b7f81423018c955d3723` ?

**Comment by ClashAlex** [comment]
Ah, there is no LP for this token, it has not been listed yet.

The screenshot is taken from the honey token in my wallet when I connect my wallet to minswap
________________________________

**Comment by ClashAlex** [comment]
Ok, thanks for checking anyway. The image shows up fine in my wallet but when I connect my wallet to a dex like minswap and view the token, there is no logo and just a ? sign.

Maybe this would change if there was a LP for the token. Thank you for your help anyway
________________________________

**Comment by Godspeed-exe** [comment]
Yeaaah, i think they fetch that from their local cache.. so until they refresh from the API it will show the question mark.

**Pull request merged**
