### PR TITLE
AAAHHH can't start over (adding 4 tokens...)

### PR DESCRIPTION
**Pull request by GabrielTexier23071997**
# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Review by crptmppt — CHANGES_REQUESTED** [review]
Right now PRs have to be manually processed and have a separate review setup which cannot handle multiple files. Accordingly PRs with more than one mapping file will be closed to prevent overloading the process.
Thank you for resubmitting your mappings as individual PRs for processing (making sure they clear the automated checks!)

**Comment by GabrielTexier23071997** [comment]
Thank You

**Comment by GabrielTexier23071997** [comment]
Hey, it maybe that only one will pass... is there a way to start over (I did at first in a rush for work) 
Thanks

**Comment by crptmppt** [comment]
closing this PR - thanks for submitting new individual PRs per metadata mapping to a token.

**Pull request closed without merging**
