### PR TITLE
Removes a mapping for the old BYNET token

### PR DESCRIPTION
**Pull request by ssledz**
# Pull Request Template

## Description

Removes a mapping for the old BYNET token by Byron Network

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by cleanerm5** [comment]
Hi @ssledz 

You need to increment the sequence number of every changed property before the signing.

**Comment by ssledz** [comment]
> Hi @ssledz
> 
> You need to increment the sequence number of every changed property before the signing.

Hi I already did this. I want to remove this mapping from the registry so I updated the name and description to 'VOID' and incremented the sequence number for those two properties.

I used the following recipe https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-delete-my-entry-from-the-registry%3F

```
token-metadata-creator entry 99a86d3c27d1bd39d74985084fb6e5f2af77f0d169b7c1f726c5581542594e4554 --name "VOID" --description "VOID"
token-metadata-creator entry 99a86d3c27d1bd39d74985084fb6e5f2af77f0d169b7c1f726c5581542594e4554 -a policy.skey
token-metadata-creator entry 99a86d3c27d1bd39d74985084fb6e5f2af77f0d169b7c1f726c5581542594e4554 --finalize
```

I have double-checked the signatures and they were changed only for name & description.

What wrong is with this procedure?

**Comment by ssledz** [comment]
I think I know what is wrong

```
token-metadata-creator validate
```

fails because of double values in `signatures` sections. When I remove double values the validation passes.

snippet
```
token-metadata-creator entry 99a86d3c27d1bd39d74985084fb6e5f2af77f0d169b7c1f726c5581542594e4554 --name "VOID" --description "VOID"
token-metadata-creator entry 99a86d3c27d1bd39d74985084fb6e5f2af77f0d169b7c1f726c5581542594e4554 -a policy.skey
token-metadata-creator entry 99a86d3c27d1bd39d74985084fb6e5f2af77f0d169b7c1f726c5581542594e4554 --finalize
```
doubles the `signatures` entries

for example before update, even if I don't change url property I have

```
    "url": {
        "sequenceNumber": 0,
        "value": "https://byron.network",
        "signatures": [
            {
                "signature": "bd47e69abec6fe92aab32eb0357956b72699a726af207aa794a37c766f8c8778cee25c2a361dd326c425b398d25e5667971ea156aee7c4f154b5acbc60e2b505",
                "publicKey": "850d3bcfe0d5022761982a610a9ced17f2a18e9c86cf3d0a5f5f7a2c896d63da"
            }
        ]
    },

```

and after

```
    "url": {
        "sequenceNumber": 0,
        "value": "https://byron.network",
        "signatures": [
            {
                "signature": "bd47e69abec6fe92aab32eb0357956b72699a726af207aa794a37c766f8c8778cee25c2a361dd326c425b398d25e5667971ea156aee7c4f154b5acbc60e2b505",
                "publicKey": "850d3bcfe0d5022761982a610a9ced17f2a18e9c86cf3d0a5f5f7a2c896d63da"
            },
            {
                "signature": "bd47e69abec6fe92aab32eb0357956b72699a726af207aa794a37c766f8c8778cee25c2a361dd326c425b398d25e5667971ea156aee7c4f154b5acbc60e2b505",
                "publicKey": "850d3bcfe0d5022761982a610a9ced17f2a18e9c86cf3d0a5f5f7a2c896d63da"
            }
        ]
    },
```

`signatures` entries are doubled.

**Comment by cleanerm5** [comment]
Hi @ssledz 

thanks for the detailed report! Much appreciated. I will double check on my end and after confirmation add it to the Wiki so users are aware of it (till we fixed it).

Many thanks

**Review by cleanerm5 — APPROVED** [review]

**Comment by cleanerm5** [comment]
Deletion implemented with #2430

**Pull request merged**
