### PR TITLE
BABY SHIB MOON PROJECT

### PR DESCRIPTION
**Pull request by LondonPass2024**
# Pull Request Template

## Description

Registration request for the BABY SHIB MOON PROJECT token.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by Godspeed-exe** [comment]
Hello @LondonPass2024 

Your submission is passing validation. But I noticed that you minted a supply of 8.000.000.000. This is also mentioned on your website tokenomics. But in your submission you have configured a Decimals value of 2. This will result in the supply only becoming 80.000.000(,00) - I feel like you want to have a look at this detail before we merge.

Let me know what you want to do!

**Review by Kartiiyer12 — APPROVED** [review]

**Comment by LondonPass2024** [comment]
Hi Godspeed-exe, you're quite right. My mistake, could you change this to the right decimal so that 8,000,000,000 token are created. So I know in future, is this a decimal of 1 that should be used?

**Comment by Godspeed-exe** [comment]
Hello @LondonPass2024 

I can't make any changes on our end, but on your end you have to:
- change the value for Decimals to 0 (instead of 2)
- go through the signing process again (since the value has changed the signature will also be different)
- upload the changed  file to your repo
- create another pull request

Let me know if you have any questions!

**Comment by Godspeed-exe** [comment]
@LondonPass2024 

It seems @Kartiiyer12 has approved and merged this request already. So you'll have to create an update for this. When updating please read this [How to section](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-update-my-entry-in-the-registry%3F) on the Wiki. Spoiler:  you need to increment the SequenceNumber values from 0 to 1. 

Let me know if you have any questions!

**Comment by LondonPass2024** [comment]
Many thanks for the response Godspeed-exe. I think i can leave it the way it is and change my website tokenomics details. Presuming I'll therefore have 80,000,000 tokens available? I guess this wont have any impact on setting up a Pool for selling them and the public still can purchase them in single tokens?

**Pull request merged**
