### PR TITLE
Create d55bf9d2ad12cc55e4ed29d97c64dba0e4905d3c80f800449f3d51f0436861…

### PR DESCRIPTION
**Pull request by Daawesomedrummer098**
…6e6765.json

Try 29 "Signature" is signed by Public Key

# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by Kartiiyer12** [comment]
Hi @Daawesomedrummer098,

There is an issue with the location of the file. There is multiple hierarchy for mappings folder but the expectation is just 

mappings/d55bf9d2ad12cc55e4ed29d97c64dba0e4905d3c80f800449f3d51f04368616e6765.json.

Please correct this and re-submit.

**Comment by Godspeed-exe** [comment]
@Daawesomedrummer098 

Your "signature" values are an identical copy of your public key.. This is not correct. 

How this works process (on your side) should work:
- it takes a value
- you sign it with your private key (please don't share it here)
- the above step generates a signature, which can be verified with your public key
- the **signature** and **public** key have to be embedded into this submission.

The guides & tools shared in earlier attempts should just guide you through this and create a useful result in a few steps.
Please have a look at the steps which are shared in earlier submissions and compare other pull requests from others.

**Comment by VladislavKudrin** [comment]
@Daawesomedrummer098,

The "token-metadata-creator --finalize" step is crucial. It will show you any issues with your submission before you create a merge request. If this step creates a JSON file without ".draft" in the file name, it means the JSON file is ready for submission and should pass our verification step.

**Comment by VladislavKudrin** [comment]
@Daawesomedrummer098 

please take a look at your path. It should be mappings and not mappings/mappings.
Also, you can find help in this [video](https://www.youtube.com/watch?v=lZBGTY_luzo&t=538s&ab_channel=%5BMnM%5DMinimumFeeCharityPool-Cardano), which should explain how to submit your json correctly

**Comment by Daawesomedrummer098** [comment]
Is there any tools that I can use that don't require me to run a node?
Everything I saw you guys linked is like super complex code or Haskell or
python or something I have no clue how to understand.

Is there anything a guy who is just trying to verify a Token get passed
this signature step without running a node?

**Comment by Godspeed-exe** [comment]
Hello @Daawesomedrummer098 

you don’t need to run a node to generate these signatures.
Vlad above has linked a YouTube video which goes through the steps using the token-metadata-generator. This should be a few simple steps:
- download the tool
- Run the steps
- Upload the generated file to your repo, with the right name, in the right place
- Create new pull request

**Comment by Godspeed-exe** [comment]
Closing since no reply, feel free to reopen if you have any questions!

Happy new year!

**Comment by Daawesomedrummer098** [comment]
Is there any tools that I can use that don't require me to run a node?
Everything I saw you guys linked is like super complex code or Haskell or
python or something I have no clue how to understand.

Is there anything a guy who is just trying to verify a Token get passed
this signature step without running a node?

**Comment by Godspeed-exe** [comment]
Hello @Daawesomedrummer098 

I think we replied above:

you don’t need to run a node to generate these signatures.
Vlad above has linked a YouTube video which goes through the steps using the token-metadata-generator. This should be a few simple steps:

download the tool
Run the steps
Upload the generated file to your repo, with the right name, in the right place
Create new pull request

**Pull request closed without merging**
