### PR TITLE
HalalBroker Final Version

### PR DESCRIPTION
**Pull request by 7robbie5**
# Pull Request Template

## Description

HalalBroker

Deletion request:
Deletion file for incorrect entry (9a3c722722dda2f407d639c5cda46845c9090f204b61677765d1279348616c616c2042726f6b6572)

Registration request:
New file for correct entry (9a3c722722dda2f407d639c5cda46845c9090f204b61677765d1279348616c616c42726f6b6572)

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [x] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by 7robbie5** [comment]
mappings/da2f0678f09b807e93048e9157cd94be794c995ba1c1ef5a0ca8b31c.json is the old file. Which we deleted last time?

**Comment by cleanerm5** [comment]
@7robbie5 yes. that file got deleted.

**Comment by cleanerm5** [comment]
Please remove da2f... from the PR and for mappings/9a3c722722dda2f407d639c5cda46845c9090f204b61677765d1279348616c616c2042726f6b6572.json you need to also increment the sequenceNumber by 1 for the changed properties before signing the file again.

**Comment by 7robbie5** [comment]
I added the void file and seq +1 for mappings/9a3c722722dda2f407d639c5cda46845c9090f204b61677765d1279348616c616c2042726f6b6572.json and added the new correct registry file with would be mappings/9a3c722722dda2f407d639c5cda46845c9090f204b61677765d1279348616c616c42726f6b6572.json

**Comment by 7robbie5** [comment]
https://tokens.cardano.org/metadata/9a3c722722dda2f407d639c5cda46845c9090f204b61677765d1279348616c616c42726f6b6572 still not visible. I deleted the original one. But they send me an incorrect one. So i did a new deletion file and added the last version which should be visible at https://tokens.cardano.org/metadata/9a3c722722dda2f407d639c5cda46845c9090f204b61677765d1279348616c616c42726f6b6572

**Comment by cleanerm5** [comment]
Hi @7robbie5 
I merged the new meta data with PR #2050 

The "VOID" request file was still invalid as for the "non-void"/"non-changed" properties the signature was inserted twice. I created a corrected version by deleting the doubled signature part and validation ran through with #2051 The actual deletion was done with #2052 

Now your new data should be available as soon as the sync has happened.

**Comment by 7robbie5** [comment]
Thnx my friend. You are a real "Cleaner" haha. Thnx again.

**Pull request closed without merging**
