### PR TITLE
CAT-DANO

### PR DESCRIPTION
**Pull request by petloverstake**
# Pull Request Template

## Description

CAT-DANO Token for PetLoverStake PET-Universe

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Review by petloverstake — COMMENTED** [review]
ok

**Review by petloverstake — COMMENTED** [review]
It's Ok

**Comment by cleanerm5** [comment]
Hi @petloverstake 

please remove the ".draft" ending of the file. Looks like you did not do the last step described in [here](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-to-prepare-an-entry-for-the-registry-%28NA-policy-script%29).

**Comment by petloverstake** [comment]
Sorry, my first time, it's a complex process...

**Review by petloverstake — COMMENTED** [review]
Hi, this is the json.

**Review by cleanerm5 — APPROVED** [review]

**Pull request merged**
