### PR TITLE
Create d55bf9d2ad12cc55e4ed29d97c64dba0e4905d3c80f800449f3d51f0.json

### PR DESCRIPTION
**Pull request by Daawesomedrummer098**
Update Image

# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by VladislavKudrin** [comment]
Hey @Daawesomedrummer098,

there are a couple of things that need to be changed:

1. You did not put asset name at the end of your policyID, hence you are creating a new file and not updating the old one. The filename should contain subject - {policyid}{assetName}.json 
In your case, it should be: d55bf9d2ad12cc55e4ed29d97c64dba0e4905d3c80f800449f3d51f04368616e6765.json
2. If you update a value, you should increment "sequenceNumber" by 1, update the value, and sign it again. Please refer to this guide: https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-update-my-entry-in-the-registry%3F

Feel free to update your PR!

**Comment by Daawesomedrummer098** [comment]
[image: Screenshot 2024-01-22 at 1.08.30 PM.png]Hmm seems like I am not
able to use that name you fixed for me. This is making a new pr. Is there
anything else I can try?

**Comment by Godspeed-exe** [comment]
Hello @Daawesomedrummer098 

When you reply by email we don't see the attached screenshots, we only see "[image: Screenshot 2024-01-22 at 1.08.30 PM.png]" as text.
You should:
- either update the file that you already have in your old fork
- create a new PR

- create another fork of the repo and upload the new file
- create a new PR

**Comment by Daawesomedrummer098** [comment]
Could not upload or figure out how to fork, But I added it here :
https://github.com/VYFI/cardano-token-registry/pull/2

**Comment by VladislavKudrin** [comment]
Hi @Daawesomedrummer098,

you have the correct filename and updated logo in your fork [here](https://github.com/Daawesomedrummer098/cardano-token-registry/commit/ee9c0a9c49cadf5519a5c3b66b39d955a85b9b27). 
What you need to do is follow the update guide i shared earlier and increment sequenceNumber, then sign it again and upload the file to your fork.
After that, you can create a new PR.

**Comment by Daawesomedrummer098** [comment]
Okay I just Tried to do that here :
https://github.com/Daawesomedrummer098/cardano-token-registry/pull/1

**Comment by Kartiiyer12** [comment]
Hi @Daawesomedrummer098 The file name is not correct, change it to d55bf9d2ad12cc55e4ed29d97c64dba0e4905d3c80f800449f3d51f04368616e6765.json as it should include both the base16-encoded policyId + base16-encoded assetName.

**Comment by Godspeed-exe** [comment]
@Daawesomedrummer098 validation failed because you renamed the file instead of putting in the folder….

**Comment by Godspeed-exe** [comment]
Please check out the validation process upon submitting and figure out why it’s not passing.

**Comment by Godspeed-exe** [comment]
Closed because of no reaction. Feel free to open a new PR when it's fixed.

**Comment by Daawesomedrummer098** [comment]
Sorry just getting back to this, I think I did it here :
https://github.com/Daawesomedrummer098/cardano-token-registry/commit/f130c2a6927e20715fe6b517563154a820cf7d14

**Comment by Godspeed-exe** [comment]
@Daawesomedrummer098 can you do a pull request? Thanks!

**Comment by Daawesomedrummer098** [comment]
I'm not able to edit my other PR, not able to upload New PR on my fork, and
not able to make a new fork.

Should I try with a new GitHub account?

**Comment by Godspeed-exe** [comment]
You have to:
- do changes on your fork (I think you did this, as you mentioned)
- Then create a new PR here, you can’t edit this one because it’s closed 


New GitHub should not be necessary

**Comment by Daawesomedrummer098** [comment]
Can you help direct and link me to the one I need to Change?

I honestly can barely navigate github and have done so many different PR`s
that Im lost at this point.

The only pr that looked Right and was the one you guys want me to update Im
not able to Edit at all, I get a error message anytime I try to made any
changes to the code

**Comment by Godspeed-exe** [comment]
Below files need to be modified / updated / deleted:

- https://github.com/Daawesomedrummer098/cardano-token-registry/blob/master/Change - this file should be deleted.
- After deleting the above file in your repo you can come to this repo and "create new pull request". 
- after the PR the automatic validation will verify the values and signatures and this can be merged

**Comment by Daawesomedrummer098** [comment]
Okay, edited it :
https://github.com/Daawesomedrummer098/cardano-token-registry/pull/5

**Pull request closed without merging**
