### PR TITLE
Add STADA token

### PR DESCRIPTION
**Pull request by Rayvid**
# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by cleanerm5** [comment]
Hi @Rayvid 

the submitted file is not valid. The file ending (.json) is missing and the subject value consists only of the policyid without the "name" part being added.

Please follow the instructions provided in the [Wiki](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-to-prepare-an-entry-for-the-registry-%28NA-policy-script%29) and let me know if you need more assistance.

**Comment by Rayvid** [comment]
Thanks pushed rename

**Comment by Rayvid** [comment]
Sorry now i understood what do you mean by adding asset name to the file name - changed again, please rerun when possible, thanks

**Comment by cleanerm5** [comment]
Hi @Rayvid 

the value given in the policy field and the subject field do not match. The first 28 bytes of the subject must match the Blake2b 224 hash of the CBOR serialized policy which for your policy script would be `1d941951b4cb5b9bfea53ab69080b61aa8fbdb5fa13029fc8c67122f`

Any reason why you are not using the correct policy ID value (which is the Blake2b 224 hash of the CBOR serialized policy)?

Let me know if you need more support.

**Comment by Rayvid** [comment]
Fixed policy hashing, sorry for not getting it right so long

**Review by cleanerm5 — APPROVED** [review]

**Pull request merged**
