### PR TITLE
Updating MACH token entry

### PR DESCRIPTION
**Pull request by rafek47**
changing decimals to 0

# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [X] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by cleanerm5** [comment]
Hi @rafek47 

besides changing the value and updating the signature you also need to increment the sequenceNumber (in your case to 1) to pass the validation.

**Comment by rafek47** [comment]
Oh, yes. I see. Thank you so much. Just updated.

**Comment by cleanerm5** [comment]
@rafek47 I assume you did not sign the value again after incrementing the sequence number. The sequence number is part of the message that gets signed (actually it is the subject, propertyName, sequenceNumber and value that gets signed together).

So after changing the sequence number you need to sign the data again.

**Comment by rafek47** [comment]
I've just realized that too. Thanks. 
Just signed and checks passed. Thanks.

**Review by cleanerm5 — APPROVED** [review]

**Pull request merged**
