### PR TITLE
ADAEAGLE TOKEN SUBMISSION

### PR DESCRIPTION
**Pull request by SAQSSS**
# Pull Request Template

## Description

Please ADAEAGLE TOKEN Approve , many thanks !

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by Godspeed-exe** [comment]
hello @SAQSSS 

This PR is not passing the automatic validation process because your file does not have the correct name. Can you modify this to {your_subject}.json ?

Thanks!

**Comment by SAQSSS** [comment]
I fixed it

[image: Biểu tượng Cộng đồng đã xác minh]
 , thanks


Vào CN, 4 thg 2, 2024 vào lúc 21:42 Michiel B ***@***.***>
đã viết:

**Comment by Godspeed-exe** [comment]
Hello @SAQSSS 

You made a modification IN the file, you didn't change the name.
Please:
- correct the content of the file, verify that it's valid JSON format through https://jsonlint.com/
- correct the filename to match the subject value in your file.

**Comment by Godspeed-exe** [comment]
Closed because of no reaction. Feel free to open a new PR when it's fixed.

**Pull request closed without merging**
