### PR TITLE
TWT Registry

### PR DESCRIPTION
**Pull request by teslasworld**
Subject: 3c307d77a4a264ce4df8687803dde19d9fb78bca19a586c43af4e7b65457547465736c6173776f726c64
Name: Tesla's World Token
Description: Creating an ecosystem based on technological solutions that are focused on renewable energy and food security, as well as a balanced relationship with nature.
Policy: 3c307d77a4a264ce4df8687803dde19d9fb78bca19a586c43af4e7b6545754
Ticker: TWT

### CODE REVIEW

**Comment by cleanerm5** [comment]
Hi @teslasworld 

you forgot to increment the sequenceNumber of the changed properties. That's why the validation fails.

**Comment by teslasworld** [comment]
can you tell me about the change properties please are you referring to...
thanks

**Comment by teslasworld** [comment]
“Hello can you please clarify what you mean by sequence number increment,
no properties have been changed

**Comment by cleanerm5** [comment]
Hi @teslasworld 

sorry my fault. That part looks ok but the renaming is not allowed. You must add the new file and follow the instructions provided in the [Wiki](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-delete-my-entry-from-the-registry%3F) to delete the one that shall be renamed in order to delete it.

**Comment by cleanerm5** [comment]
Hi @teslasworld 

please contact me directly via Telegram or E-Mail if you still need support.

**Comment by teslasworld** [comment]
“hello I am from Tesla’s World Token, I previously submitted the JSON file
for verification with incorrect information (typos)

What is the process to have this corrected?”

**Comment by cleanerm5** [comment]
Please drop me an E-Mail to sebastian.bode@cardanofoundation.org

**Pull request closed without merging**
