### PR TITLE
fixed filename and subject value

### PR DESCRIPTION
**Pull request by wcatz**
# Pull Request Template

## Description

Matti accidentally added '20' into the filename and subject. This pr renames the file json and removes the 20 at the end of the subject.

## Type of change

- [x ] Metadata related change
- [x ] Other

## Checklist:

- [ x] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by wcatz** [comment]
Hello

Is there anything I can do to help this pr along. The rest of th Tosidrop team and community are inquiring about it.

Best regards
Wayne

**Comment by wolf31o2** [comment]
Just throwing out a :+1: as another TosiDrop core dev, stating this is approved and not someone randomly trying to change the metadata for the token.

**Comment by cleanerm5** [comment]
Hi @wcatz 

problem is, if you changed the subject (removing the 20/blank) you need to sign the metadata file again because the subject is part of the signature. If you do this and file a PR with the properly signed file and still the issue with the "rename" remains I can do the PR for you. But I cannot do the signing itself.

Let me know if you need more support or a call on this. I saw you already reached out via E-Mail.

**Comment by wcatz** [comment]
There was some confusion, it was not Mati after all who minted and submitted. I will reach out to the service that was used and request the correction.

Apologies for the confusion

**Pull request closed without merging**
