### PR TITLE
Remove mistakenly added metadata 

### PR DESCRIPTION
**Pull request by time2devnull**
as per advice: https://github.com/cardano-foundation/cardano-token-registry/pull/5#issuecomment-794568576

# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [x] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by crptmppt** [comment]
You cannot rename the filename itself, rather, see the wiki entry on [how to delete an entry](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-delete-my-entry-from-the-registry%3F)
=> Modify the existing PR and change name/Description to 'VOID'

**Review by crptmppt — CHANGES_REQUESTED** [review]
leave filename and change name / description to VOID in the mapping

**Comment by time2devnull** [comment]
> leave filename and change name / description to VOID in the mapping

This has been corrected now, thank you!

**Comment by crptmppt** [comment]
> > leave filename and change name / description to VOID in the mapping
> 
> This has been corrected now, thank you!

note that you need to regenerate the json file itself: see "[How do I update my entry in the registry](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-do-I-update-my-entry-in-the-registry%3F)" from the wiki.
Simply altering the mapping field directly will not pass the CI tests - thank you for your patience!

**Comment by time2devnull** [comment]
@crptmppt added changes (:

**Review by crptmppt — APPROVED** [review]

**Pull request merged**
