### PR TITLE
GNUG token website added (https://www.gnug.app) with 256x256 resolution token logo.

### PR DESCRIPTION
**Pull request by nigelflaming**
# Pull Request Template

## Description

GNUG token website added and new 256x256 resolution token logo added.

## Type of change

- [x] Metadata related change
- [x] Other

## Checklist:

- [x] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by nigelflaming** [comment]
$GNUG token - Website added. 256x256 resolution token logo

**Comment by cleanerm5** [comment]
Hi @nigelflaming 

the file needs to go in the "mappings" folder and also the " (2)" at the end of the filename before the filetype extension needs to be removed.

**Comment by nigelflaming** [comment]
> Hi @nigelflaming
> 
> the file needs to go in the "mappings" folder and also the " (2)" at the end of the filename before the filetype extension needs to be removed.

Thanks for the correction.

**Comment by nigelflaming** [comment]
reupload with corrections

**Pull request closed without merging**
