### PR TITLE
KINGCrocodile TOKEN submission

### PR DESCRIPTION
**Pull request by Proximang88**
# Pull Request Template

## Description

Please KINGCrocodile TOKEN approve . thanks team ! 

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by Proximang88** [comment]
> Hello @Proximang88
> 
> The Brave.json file is still in your pull request, can you remove this and try again?
> 
> Thanks!


I don't know how to do this can you guide me

**Comment by VladislavKudrin** [comment]
Hey @Proximang88,

go to your fork, open Brave.json, and you will see three dots on the top right - choose "Delete file". 
This will create a new commit and you can update the PR

**Comment by Godspeed-exe** [comment]
@Proximang88 

You have to delete this file: https://github.com/Proximang88/cardano-token-registry/blob/master/mappings/Brave.json
Then create a new pull request here.

**Comment by Godspeed-exe** [comment]
Closed because no respone

**Pull request closed without merging**
