### PR TITLE
Black Doge Meta Data Update

### PR DESCRIPTION
**Pull request by dorjepadma**
# Pull Request Template

## Description

An updating of Black Doge metadata

## Type of change

[ x] Metadata related change
Changed "url" from "value:: "https://blackdoge.Coin" to "https://blackdoge.io"
Changed "decimals" from "sequenceNumber": 0 to "sequenceNumber": 1
Changed "decimals" from "value": 2 to "value": 0
Changed "logo" from "sequenceNumber": 0 to "sequenceNumber": 1
Changed "description" from "value": Black Doge (Bdoge) is a token....
to
"value": Black Doge Coin ($BDOGE) is the official utility....
Updated meta data key

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Review by BlackDogeFather — APPROVED** [review]

**Review by BlackDogeFather — APPROVED** [review]

**Review by BlackDogeFather — APPROVED** [review]
Dear admins. Please approve this merge. Thank you so much and happy holidays!

**Comment by BlackDogeFather** [comment]
Is there any additional action required on our end to have these changes approved? It’s a relatively urgently needed update. Thank you!!

**Comment by dorjepadma** [comment]
Hello, we were informed that this failed checks because of Metadata not in our pull request but in the pull request of another mappings file. Would you please merge our file, which passes all tests and has been thoroughly vetted It is file f555c46bad0731d080c9381d7fff6f82839946a66bd070d185e1ea2f42444f4745. If we have been misinformed and have an error that needs correcting in our mappings file, please let us know. There is a critical error in our token ecosystem file and this pull request fixes it.

**Comment by BlackDogeFather** [comment]
Closed in a good way!?!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dorjepadma** [comment]
Closed in the way that Anslum said to close all pull requests and he will work directly with Cardano Token Registry because they communicated some further issues and so asked me to close all of my pull requests.

**Pull request closed without merging**
