### PR TITLE
ERMO

### PR DESCRIPTION
**Pull request by cardano-tools-nft**
# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Review by Mandolab — COMMENTED** [review]
Is there anything here that I must do? I don’t know why was this review open.
I just will accept. If you have any requests for us to change something please let me know.
Thanks.

**Review by Mandolab — APPROVED** [review]

**Comment by Mandolab** [comment]
Is it something wrong here with $ERMO to get merged?

**Comment by Mandolab** [comment]
Hi!
How long does it take normally to merge?

**Comment by wutzebaer** [comment]
> Hi! How long does it take normally to merge?

Hm i would say two business days

**Review by Kartiiyer12 — APPROVED** [review]

**Comment by Mandolab** [comment]
Hi;
Where can I found the keys for this policy?
Is it possible to lock it?

**Pull request merged**
