### PR TITLE
Add Pepes Mom to registry 

### PR DESCRIPTION
**Pull request by How-Do-You-Want-To-Do-This**
Add Pepes Mom to registry

### CODE REVIEW

**Comment by VladislavKudrin** [comment]
Hi @How-Do-You-Want-To-Do-This,

1. Your json file should have .json as the extension.
2. The policy field is not policyID, but base16-encoded CBOR representation of the monetary policy script

Could you change that and update the PR? Also, if your issue #4398 is solved - close it.

Thanks.

**Comment by How-Do-You-Want-To-Do-This** [comment]
Regarding #2

 2. The policy field is not policyID, but base16-encoded CBOR representation of the monetary policy script

Could you clarify/ further explain this/ give insight on how to do this? The only thing I have to verify ownership are two vkeys

**Comment by VladislavKudrin** [comment]
@How-Do-You-Want-To-Do-This,

this is your policy [script](https://cexplorer.io/tx/45b58b21f7e79c7e12fcebce0fe9733a9c51fe1d873add1de00e1d5ea92f9daa/script#data):
```json
{
    "type": "all",
    "scripts": [
        {
            "slot": 119914693,
            "type": "before"
        },
        {
            "type": "sig",
            "keyHash": "55b82c0fa98ad7867b2612829d3a65285174b8e084a6a2aa308cf833"
        }
    ]
}
```

You should execute this, having the above policy in policy.json:
`token-metadata-creator entry {your_subject} \
  --policy policy.json`

But if you don't have the signing keys from the policy - you will not be able to verify the ownership.

**Comment by VladislavKudrin** [comment]
@How-Do-You-Want-To-Do-This,

no, please do this and follow the [guide](https://github.com/cardano-foundation/cardano-token-registry/wiki/How-to-prepare-an-entry-for-the-registry-%28NA-policy-script%29)

> @How-Do-You-Want-To-Do-This,
> 
> this is your policy [script](https://cexplorer.io/tx/45b58b21f7e79c7e12fcebce0fe9733a9c51fe1d873add1de00e1d5ea92f9daa/script#data):
> 
> ```json
> {
>     "type": "all",
>     "scripts": [
>         {
>             "slot": 119914693,
>             "type": "before"
>         },
>         {
>             "type": "sig",
>             "keyHash": "55b82c0fa98ad7867b2612829d3a65285174b8e084a6a2aa308cf833"
>         }
>     ]
> }
> ```
> 
> You should execute this, having the above policy in policy.json: `token-metadata-creator entry {your_subject} \ --policy policy.json`
> 
> But if you don't have the signing keys from the policy - you will not be able to verify the ownership.

**Pull request closed without merging**
