### PR TITLE
Pull request for BABYSHIB Logo

### PR DESCRIPTION
**Pull request by LondonPass2024**
# Pull Request Template

## Description

Sorry for creating dulplicates. Please use the JSON file (any) submitted today and ignore the others. The json now contains the 'logo' section.

## Type of change

- [ ] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the GitHub Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by LondonPass2024** [comment]
Hi Godspeed, so i created a new JSON file with the right logo and signature but i received a metadata validation failure. Did I do something wrong?

**Comment by Godspeed-exe** [comment]
@LondonPass2024 

It seems like you are trying to merge 2 files.
1. in the /mappings folder - this is okay and the file looks good 
2. in the root of the repo - **this is not allowed, if you remove this I think it should be okay**

Go ahead and modify it, I'll keep an eye on it;

**Comment by LondonPass2024** [comment]
Silly question, but how do i remove it?

**Comment by LondonPass2024** [comment]
Ok, think i've done the deletion (I hope :) )

**Review by Godspeed-exe — APPROVED** [review]

**Comment by Godspeed-exe** [comment]
LOOKING GOOD!

**Comment by LondonPass2024** [comment]
Thanks again for all your help! Much appreciated.

**Pull request merged**
